const router = require('express').Router()
const ctrl = require('../controllers/supervision.controller')
const management = require('../controllers/supervisionManagement.controller')
const daily = require('../controllers/supervisionDaily.controller')
const exceptions = require('../controllers/supervisionException.controller')
const shiftRecords = require('../controllers/supervisionShiftRecord.controller')
const studentStart = require('../controllers/studentStartFollowup.controller')
const academic = require('../controllers/academicObservation.controller')
const academicV3 = require('../controllers/academicV3.controller')
const periodic = require('../controllers/academicPeriodic.controller')
const cohorts = require('../controllers/supervisionCohort.controller')
const profiles = require('../controllers/supervisionProfile.controller')
const { authenticate } = require('../middleware/auth.middleware')
const { requirePermission } = require('../middleware/rbac.middleware')

router.use(authenticate)
router.get('/teacher-guidance', academic.teacherInbox)
router.post('/teacher-guidance/:id/reply', academic.teacherReply)
router.get('/academic-directives', academicV3.listDirectives)
router.post('/academic-directives/:id/reply', academicV3.replyDirective)
router.get('/academic-plans', academicV3.listPlans)
router.get('/academic-students/:studentId/overview', academicV3.studentOverview)
router.use(requirePermission('supervision.view'))
router.get('/profiles/teacher/:id', profiles.teacher)
router.get('/profiles/student/:id', profiles.student)
router.get('/periodic-metrics', periodic.metrics)
router.get('/periodic-reports', periodic.list)
router.get('/periodic-reports/:id', periodic.detail)
router.post('/periodic-reports', periodic.save)
router.post('/periodic-reports/:id/submit', periodic.submit)
router.post('/periodic-reports/:id/review', periodic.review)
router.post('/periodic-reports/:id/correct', periodic.correct)
router.get('/academic-search', periodic.search)
router.get('/academic-recognition', periodic.recognition)
router.put('/academic-recognition', periodic.saveRecognition)
router.get('/academic-students/search', academicV3.findStudents)
router.get('/academic-directive-recipients/search', academicV3.searchDirectiveRecipients)
router.post('/academic-plans', academicV3.savePlan)
router.patch('/academic-plans/:id/status', academicV3.publishPlan)
router.patch('/academic-plans/:id/milestones/:milestoneId', academicV3.updateMilestone)
router.get('/academic-teachers/:teacherId/overview', academicV3.teacherOverview)
router.get('/academic-supervisors/:supervisorId/overview', academicV3.supervisorOverview)
router.post('/academic-development', academicV3.createDevelopment)
router.patch('/academic-development/:id', academicV3.updateDevelopment)
router.post('/academic-directives', academicV3.createDirective)
router.get('/academic-directives/:id/receipts', academicV3.directiveReceipts)
router.post('/academic-directives/:id/verify', academicV3.verifyDirective)
router.get('/academic-reports', academic.list)
router.get('/academic-reports/:id', academic.detail)
router.put('/academic-reports/session/:sessionId', academic.save)
router.post('/academic-reports/:id/submit', academic.submit)
router.post('/academic-reports/:id/review', academic.review)
router.patch('/academic-reports/:id/correct', academic.managerCorrect)
router.get('/people', ctrl.listPeople)
router.patch('/people/:id', requirePermission('supervision.manage'), management.updatePerson)
router.get('/coverage', management.coverage)
router.get('/daily-sessions', daily.list)
router.get('/new-students', studentStart.list)
router.post('/new-students/:studentId/stabilize', studentStart.stabilize)
router.get('/shift-records', shiftRecords.list)
router.get('/shift-handoffs', shiftRecords.handoffFeed)
router.get('/shift-records/:shiftId', shiftRecords.detail)
router.post('/shift-records/:shiftId/check-in', shiftRecords.checkIn)
router.post('/shift-records/:shiftId/check-out', shiftRecords.checkOut)
router.post('/shift-records/:shiftId/handoff', shiftRecords.handoff)
router.patch('/shift-records/:shiftId/report-draft', shiftRecords.saveReportDraft)
router.post('/shift-records/:shiftId/report', shiftRecords.submitReport)
router.get('/exceptions', exceptions.list)
router.post('/exceptions', exceptions.create)
router.post('/exceptions/:id/apply', exceptions.apply)
router.post('/exceptions/:id/retry', exceptions.retry)
router.post('/exceptions/:id/resolve', exceptions.resolve)
router.patch('/exceptions/:id/owner', exceptions.reassign)
router.get('/adjustment-requests', exceptions.listAdjustments)
router.post('/adjustment-requests', exceptions.requestAdjustment)
router.post('/adjustment-requests/:id/decision', exceptions.decideAdjustment)
router.post('/adjustment-requests/:id/retry', exceptions.retryAdjustment)
router.post('/daily-dispatch', daily.dispatch)
router.post('/daily-actions', daily.createAction)
router.post('/daily-actions/:id/resolve', daily.resolveAction)
router.patch('/sessions/:sessionId/readiness', daily.updateReadiness)
router.post('/sessions/:sessionId/remind-report', daily.remindTeacherReport)
router.get('/activity', management.activity)
router.get('/settings', management.getSettings)
router.put('/settings', requirePermission('supervision.manage'), management.updateSettings)
router.get('/teachers', ctrl.listTeachers)
router.get('/students', ctrl.listStudents)
router.get('/shifts', ctrl.listShifts)
router.post('/shifts', requirePermission('supervision.manage'), ctrl.createShift)
router.patch('/shifts/:id', requirePermission('supervision.manage'), ctrl.updateShift)
router.post('/shifts/:id/cancel', requirePermission('supervision.manage'), ctrl.cancelShift)
router.get('/assignments', ctrl.listAssignments)
router.get('/cohorts', cohorts.list)
router.get('/cohorts/:id', cohorts.detail)
router.post('/cohorts', requirePermission('supervision.manage'), cohorts.create)
router.patch('/cohorts/:id', requirePermission('supervision.manage'), cohorts.update)
router.post('/cohorts/:id/members', requirePermission('supervision.manage'), cohorts.addMembers)
router.delete('/cohorts/:id/members/:studentId', requirePermission('supervision.manage'), cohorts.removeMember)
router.post('/assignments', requirePermission('supervision.manage'), ctrl.createAssignment)
router.post('/assignments/:id/replace', requirePermission('supervision.manage'), ctrl.replaceAssignment)
router.get('/assignments/:id/students', ctrl.assignmentStudents)

module.exports = router
