import { useState } from 'react'
import { useMutation } from '@tanstack/react-query'
import toast from 'react-hot-toast'
import { supervisionService } from '../../services/supervision.service.js'

const input = 'min-h-11 w-full rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm outline-none focus:border-violet-500'
const statusLabel = { open: 'تحتاج متابعة', improving: 'تحسن جارٍ', improved: 'تحسنت' }

export default function AcademicDevelopmentPanel({ personId, cases = [], onSaved }) {
  const [form, setForm] = useState({ title: '', strengths: '', improvement: '', nextAction: '' })
  const [updates, setUpdates] = useState({})
  const error = (err) => toast.error(err.response?.data?.message || 'تعذر حفظ المتابعة')
  const create = useMutation({ mutationFn: () => supervisionService.createAcademicDevelopment({ personId, ...form }),
    onSuccess: () => { toast.success('سُجلت نقطة المتابعة'); setForm({ title: '', strengths: '', improvement: '', nextAction: '' }); onSaved() }, onError: error })
  const update = useMutation({ mutationFn: ({ id, data }) => supervisionService.updateAcademicDevelopment(id, data),
    onSuccess: () => { toast.success('تحدثت حالة المتابعة'); onSaved() }, onError: error })
  return <div className="mt-4 rounded-xl border border-violet-100 p-4"><h4 className="font-bold">سجل التحسن والمتابعة</h4><p className="mt-1 text-xs text-gray-500">يسجل المدير نقطة تطوير وخطوة عمل، ثم يثبت التقدم أو التحسن مع التاريخ.</p>
    <div className="mt-3 space-y-3">{cases.map((row) => <article key={row._id} className="rounded-xl bg-gray-50 p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><strong>{row.title}</strong><span>{statusLabel[row.status]}</span></div><p className="mt-1">نقطة التطوير: {row.improvement}</p>{row.strengths && <p>نقطة القوة: {row.strengths}</p>}<p>الإجراء: {row.nextAction}</p>{row.outcome && <p className="mt-1 text-emerald-700">النتيجة: {row.outcome}</p>}<p className="mt-1 text-xs text-gray-500">آخر تحديث: {new Date(row.updatedAt).toLocaleDateString('ar-EG-u-nu-latn')} · {row.history?.length || 0} تحديثات محفوظة</p><details className="mt-2 text-xs text-gray-600"><summary className="cursor-pointer font-semibold">عرض سجل التغييرات</summary><div className="mt-2 space-y-1">{row.history?.map((entry, index) => <p key={`${row._id}-${index}`}>{new Date(entry.at).toLocaleDateString('ar-EG-u-nu-latn')} · {statusLabel[entry.status]} {entry.outcome && `· ${entry.outcome}`}</p>)}</div></details><form onSubmit={(e) => { e.preventDefault(); const draft = updates[row._id] || { status: 'improving', outcome: '' }; update.mutate({ id: row._id, data: draft }) }} className="mt-3 grid gap-2 sm:grid-cols-[150px_1fr_auto]"><select aria-label="حالة المتابعة" value={updates[row._id]?.status || 'improving'} onChange={(e) => setUpdates({ ...updates, [row._id]: { ...updates[row._id], status: e.target.value } })} className={input}><option value="open">تحتاج متابعة</option><option value="improving">تحسن جارٍ</option><option value="improved">تحسنت</option></select><input aria-label="نتيجة المتابعة" maxLength={1000} required={updates[row._id]?.status === 'improved'} value={updates[row._id]?.outcome || ''} onChange={(e) => setUpdates({ ...updates, [row._id]: { ...updates[row._id], outcome: e.target.value } })} className={input} placeholder="ما الذي تغير؟" /><button disabled={update.isPending} className="min-h-11 rounded-lg border border-violet-200 px-3 font-bold text-violet-700">تحديث</button></form></article>)}{!cases.length && <p className="text-sm text-gray-500">لا توجد نقاط متابعة مسجلة</p>}</div>
    <form onSubmit={(e) => { e.preventDefault(); create.mutate() }} className="mt-4 grid gap-2 sm:grid-cols-2"><h5 className="sm:col-span-2 text-sm font-bold">نقطة متابعة جديدة</h5><label className="text-xs">العنوان<input required maxLength={160} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} className={input} /></label><label className="text-xs">نقطة قوة<input maxLength={1000} value={form.strengths} onChange={(e) => setForm({ ...form, strengths: e.target.value })} className={input} /></label><label className="text-xs">ما يحتاج تطويرًا<input required maxLength={1000} value={form.improvement} onChange={(e) => setForm({ ...form, improvement: e.target.value })} className={input} /></label><label className="text-xs">الإجراء القادم<input required maxLength={1000} value={form.nextAction} onChange={(e) => setForm({ ...form, nextAction: e.target.value })} className={input} /></label><button disabled={create.isPending} className="min-h-11 rounded-lg bg-violet-700 px-4 text-sm font-bold text-white sm:col-span-2">حفظ نقطة المتابعة</button></form>
  </div>
}
