import { useEffect, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import toast from 'react-hot-toast'
import { CalendarClock, CheckCircle2, CircleAlert, Link2, Send, FileClock, ExternalLink, ClipboardList } from 'lucide-react'
import SupervisionDrawer from './SupervisionDrawer.jsx'
import { supervisionService } from '../../services/supervision.service.js'
import { academyDateKey, academyDayRange, formatTimeAr } from '../../utils/date.js'

const input = 'min-h-11 w-full rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm outline-none focus:border-violet-500 focus:ring-2 focus:ring-violet-100'
const categoryOptions = [['readiness', 'جاهزية الطالب والمعلم'], ['entry', 'متابعة الدخول'], ['link', 'مشكلة الرابط'], ['message', 'رسالة تحتاج إجراء'], ['teacher_report', 'تقرير المعلم']]
const statusLabels = { scheduled: 'مجدولة', ongoing: 'جارية', completed: 'انتهت', missed: 'لم تتم', no_show: 'غياب' }
const fullName = (person) => [person?.firstNameAr, person?.lastNameAr].filter(Boolean).join(' ') || '—'
const localDay = () => academyDateKey(new Date())
const rangeFor = academyDayRange
const time = formatTimeAr

const safeMeetingLink = (value) => {
  try { const url = new URL(value); return url.protocol === 'https:' ? url.href : null } catch { return null }
}

export default function SupervisionDailySection({ team, user, onOpenException, onOpenReport, initialTarget }) {
  const [day, setDay] = useState(localDay)
  const [focusedId, setFocusedId] = useState('')
  useEffect(() => { if (initialTarget?.sessionId) { setDay(academyDateKey(initialTarget.day)); setFocusedId(initialTarget.sessionId); setPage(1) } }, [initialTarget])
  const [page, setPage] = useState(1)
  const [issueFor, setIssueFor] = useState(null)
  const [ownerSearch, setOwnerSearch] = useState('')
  const [issue, setIssue] = useState({ category: 'readiness', description: '', ownerId: '' })
  const [resolving, setResolving] = useState(null)
  const [resolution, setResolution] = useState('')
  const qc = useQueryClient()
  const range = rangeFor(day)
  const key = ['supervision', 'daily', team, day, page, focusedId]
  const daily = useQuery({ queryKey: key, queryFn: () => supervisionService.dailySessions({ team, ...range, page, limit: 20, sessionId: focusedId || undefined }), refetchInterval: 30000 })
  const people = useQuery({ queryKey: ['supervision', 'daily-people', team, ownerSearch], queryFn: () => supervisionService.people({ team, active: true, search: ownerSearch, limit: 50 }), enabled: !!issueFor })
  const refresh = () => qc.invalidateQueries({ queryKey: ['supervision', 'daily'] })
  const error = (err) => toast.error(err.response?.data?.message || 'تعذّر تنفيذ الإجراء')
  const dispatch = useMutation({ mutationFn: () => supervisionService.dispatchDay(range), onSuccess: () => { toast.success('وصل إشعار الجدول إلى المشرفين الأكاديميين'); refresh() }, onError: error })
  const addIssue = useMutation({ mutationFn: () => supervisionService.createDailyAction({ team, sessionId: issueFor, ...issue }), onSuccess: () => { toast.success('سُجلت المتابعة عند المسؤول'); setIssueFor(null); setIssue({ category: 'readiness', description: '', ownerId: '' }); refresh() }, onError: error })
  const resolve = useMutation({ mutationFn: (actionId) => supervisionService.resolveDailyAction(actionId, resolution), onSuccess: () => { toast.success('أُغلقت المتابعة'); setResolving(null); setResolution(''); refresh() }, onError: error })
  const remind = useMutation({ mutationFn: (sessionId) => supervisionService.remindTeacherReport(sessionId, team), onSuccess: ({ data }) => toast.success(data.message), onError: error })
  const readiness = useMutation({ mutationFn: ({ sessionId, aspect, state }) => supervisionService.updateReadiness(sessionId, aspect, state), onSuccess: refresh, onError: error })
  const rows = daily.data?.data || []
  const owners = [...new Map([...(user?.supervisionTeam === team ? [user] : []), ...(people.data?.data || [])].filter((person) => ['manager', 'supervisor'].includes(person.supervisionPosition)).map((person) => [person._id, person])).values()]
  const canDispatch = team === 'administrative' && (user?.role === 'admin' ? user?.isPrimaryAdmin || user?.permissions?.includes('supervision.manage') : user?.supervisionTeam === team)

  return <section className="space-y-4" aria-label="تشغيل الحلقات اليومي">
    <div className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div><span className="inline-flex rounded-xl bg-violet-50 p-2 text-violet-700"><CalendarClock size={20} /></span><h2 className="mt-2 font-heading text-xl font-bold text-gray-900">حلقات اليوم</h2><p className="mt-1 text-sm leading-6 text-gray-500">قائمة حية من الحصص القائمة. بدء المعلم وفتح الرابط إشارتان من المنصة ولا يثبتان دخول اجتماع Zoom أو Meet.</p></div>
        <div className="flex w-full flex-wrap items-end gap-2 sm:w-auto"><label className="block text-sm font-semibold text-gray-700">اليوم<input type="date" value={day} onChange={(event) => { setDay(event.target.value); setFocusedId(''); setPage(1) }} className={`mt-1 ${input}`} /></label>{focusedId && <button type="button" onClick={() => setFocusedId('')} className="min-h-11 rounded-xl border px-3 text-sm">عرض كل اليوم</button>}{canDispatch && !focusedId && <button type="button" disabled={dispatch.isPending || !rows.length} onClick={() => dispatch.mutate()} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-violet-600 px-4 text-sm font-bold text-white disabled:opacity-50"><Send size={16} /> {dispatch.isPending ? 'جارٍ التسليم...' : 'تسليم الجدول للأكاديمي'}</button>}</div>
      </div>
      {daily.data?.dispatch && team === 'academic' && <p className="mt-3 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">أُرسل تنبيه بالجدول يوم {new Date(daily.data.dispatch.createdAt).toLocaleString('ar-EG')}. البيانات هنا تتحدث مع أي تغيير.</p>}
      <p className="mt-3 text-xs text-gray-500">التذكيرات داخل المنصة عند 24 ساعة وساعة و30 و15 و5 دقائق. رسائل واتساب تظل خارج المنصة حتى يتوفر تكامل معتمد.</p>
    </div>
    {daily.isLoading && <p className="rounded-xl bg-white p-5 text-sm text-gray-500">جارٍ تحميل الحلقات...</p>}
    {daily.isError && <p role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-700">تعذّر تحميل الحلقات. <button onClick={() => daily.refetch()} className="font-bold underline">إعادة المحاولة</button></p>}
    {!daily.isLoading && !daily.isError && !rows.length && <p className="rounded-xl bg-white p-8 text-center text-sm text-gray-500">لا توجد حلقات مسندة لك في هذا اليوم.</p>}
    {rows.map((row) => <article key={row._id} className="rounded-2xl border border-gray-100 bg-white p-4 shadow-sm sm:p-5">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold text-violet-700">{time(row.scheduledAt)} · {statusLabels[row.status] || row.status}{row.isMakeup ? ' · تعويض' : ''}</p><h3 className="mt-1 text-lg font-bold text-gray-900">{row.titleAr}</h3><p className="mt-1 text-sm text-gray-600">الطالب: {fullName(row.studentId)} · المعلم: {fullName(row.teacherId)}</p><p className="mt-1 text-sm text-gray-600">المشرفون: {row.supervisors?.length ? row.supervisors.map((person) => `${fullName(person)}${person.onShift ? ' (بالشيفت)' : ' (خارج الشيفت)'}`).join('، ') : 'غير مسند'}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${row.status === 'completed' ? 'bg-emerald-50 text-emerald-700' : row.status === 'ongoing' ? 'bg-sky-50 text-sky-700' : 'bg-gray-100 text-gray-700'}`}>{statusLabels[row.status] || row.status}</span></div>
      <div className="mt-4 flex flex-wrap gap-2 text-xs"><span className={`rounded-lg px-2.5 py-1.5 ${row.meetingLink ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-800'}`}><Link2 size={13} className="ml-1 inline" />{row.meetingLink ? 'الرابط موجود' : 'الرابط ناقص'}</span><span className={`rounded-lg px-2.5 py-1.5 ${row.teacherStartedAt ? 'bg-emerald-50 text-emerald-700' : 'bg-gray-100 text-gray-600'}`}>{row.teacherStartedAt ? 'المعلم أعلن البدء' : 'لم يعلن المعلم البدء'}</span><span className="rounded-lg bg-gray-100 px-2.5 py-1.5 text-gray-600">{row.studentLinkOpenedAt ? 'الطالب فتح الرابط' : 'لا توجد إشارة فتح من الطالب'}</span>{row.status === 'completed' && <span className={`rounded-lg px-2.5 py-1.5 ${row.missingTeacherReport ? 'bg-amber-50 text-amber-800' : 'bg-emerald-50 text-emerald-700'}`}>{row.missingTeacherReport ? 'تقرير المعلم مطلوب' : row.quranReportRequired === false ? 'التقرير غير مطلوب' : 'تقرير المعلم وصل'}</span>}</div>
      {row.status === 'scheduled' && new Date(row.scheduledAt) < new Date() && !row.teacherStartedAt && <p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm font-semibold text-amber-900">مر موعد الحصة ولم يعلن المعلم البدء داخل المنصة. تأكد من الحالة قبل تسجيل غياب.</p>}
      <div className="mt-3 grid gap-2 sm:grid-cols-3">{[['student', 'جاهزية الطالب'], ['teacher', 'جاهزية المعلم'], ['link', 'صلاحية الرابط']].map(([aspect, label]) => <label key={aspect} className="text-xs font-semibold text-gray-700">{label}<select disabled={!canDispatch || readiness.isPending || !['scheduled', 'ongoing'].includes(row.status)} value={row.administrativeReadiness?.[aspect] || 'unknown'} onChange={(event) => readiness.mutate({ sessionId: row._id, aspect, state: event.target.value })} className={`mt-1 ${input}`}><option value="unknown">لم تُفحص</option><option value="ready">جاهز</option><option value="issue">تحتاج متابعة</option></select></label>)}</div>
      <div className="mt-4 flex flex-wrap gap-2">{safeMeetingLink(row.meetingLink) && <a href={safeMeetingLink(row.meetingLink)} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-violet-700 px-4 text-sm font-bold text-white no-underline transition-colors hover:bg-violet-800 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-violet-700"><ExternalLink size={16} /> دخول الحلقة</a>}{team === 'academic' && user?.supervisionPosition === 'supervisor' && <button type="button" onClick={() => onOpenReport?.(row)} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-violet-200 bg-white px-4 text-sm font-bold text-violet-700 transition-colors hover:bg-violet-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-violet-700"><ClipboardList size={16} /> تقرير المتابعة R1</button>}<button type="button" onClick={() => { setIssueFor(issueFor === row._id ? null : row._id); setIssue({ category: 'readiness', description: '', ownerId: user?.supervisionTeam === team ? user._id : '' }) }} className="min-h-11 rounded-xl border border-violet-200 px-3 text-sm font-bold text-violet-700">تسجيل متابعة</button>{canDispatch && <button type="button" onClick={() => onOpenException?.(row._id)} className="min-h-11 rounded-xl border border-amber-200 px-3 text-sm font-bold text-amber-800">اعتذار أو تغيير أو تعويض</button>}{row.missingTeacherReport && <button type="button" disabled={remind.isPending} onClick={() => remind.mutate(row._id)} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-amber-200 px-3 text-sm font-bold text-amber-800 disabled:opacity-50"><FileClock size={16} /> تنبيه المعلم بالتقرير</button>}</div>
      {issueFor === row._id && <SupervisionDrawer title="تسجيل متابعة الحلقة" onClose={() => setIssueFor(null)}><form onSubmit={(event) => { event.preventDefault(); addIssue.mutate() }} className="space-y-4"><label className="text-sm font-semibold text-gray-700">نوع المتابعة<select value={issue.category} onChange={(event) => setIssue({ ...issue, category: event.target.value })} className={`mt-1 ${input}`}>{categoryOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><div><label className="text-sm font-semibold text-gray-700">بحث عن المسؤول<input value={ownerSearch} onChange={(event) => setOwnerSearch(event.target.value)} className={`mt-1 ${input}`} placeholder="الاسم أو البريد" /></label><label className="mt-2 block text-sm font-semibold text-gray-700">المسؤول<select required value={issue.ownerId} onChange={(event) => setIssue({ ...issue, ownerId: event.target.value })} className={`mt-1 ${input}`}><option value="">اختر المسؤول</option>{owners.map((person) => <option key={person._id} value={person._id}>{fullName(person)} · {person.supervisionPosition === 'manager' ? 'مدير' : 'مشرف'}</option>)}</select></label></div><label className="text-sm font-semibold text-gray-700 sm:col-span-2">ما الإجراء المطلوب؟<textarea required maxLength={1000} rows={2} value={issue.description} onChange={(event) => setIssue({ ...issue, description: event.target.value })} className={`mt-1 ${input}`} /></label><button disabled={addIssue.isPending || !issue.ownerId || !issue.description.trim()} className="min-h-11 rounded-xl bg-violet-600 px-4 text-sm font-bold text-white disabled:opacity-50">حفظ المتابعة</button></form></SupervisionDrawer>}
      {!!row.openActions?.length && <div className="mt-4 space-y-2 border-t border-gray-100 pt-4"><p className="text-sm font-bold text-gray-800">متابعات مفتوحة</p>{row.openActions.map((action) => <div key={action._id} className="rounded-xl bg-amber-50 p-3 text-sm"><p className="flex items-center gap-1 font-semibold text-amber-900"><CircleAlert size={15} /> {action.description}</p><p className="mt-1 text-xs text-amber-800">المسؤول: {fullName(action.ownerId)}</p>{(user?.role === 'admin' || user?.supervisionPosition === 'manager' || user?._id === action.ownerId?._id) && <div className="mt-2">{resolving === action._id ? <form onSubmit={(event) => { event.preventDefault(); resolve.mutate(action._id) }} className="flex flex-wrap gap-2"><input required maxLength={1000} value={resolution} onChange={(event) => setResolution(event.target.value)} placeholder="ماذا تم؟" className={`${input} flex-1`} /><button disabled={resolve.isPending || !resolution.trim()} className="min-h-11 rounded-xl bg-emerald-700 px-4 text-white disabled:opacity-50">إغلاق</button></form> : <button type="button" onClick={() => { setResolving(action._id); setResolution('') }} className="inline-flex min-h-11 items-center gap-1 font-bold text-emerald-700"><CheckCircle2 size={15} /> تسجيل الحل</button>}</div>}</div>)}</div>}
    </article>)}
    {!!daily.data?.total && <div className="flex items-center justify-between rounded-xl bg-white px-4 py-2 text-sm text-gray-600"><span>{daily.data.total} حصة · صفحة {page}</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="min-h-11 rounded-lg border px-3 disabled:opacity-40">السابق</button><button disabled={!daily.data.hasMore} onClick={() => setPage(page + 1)} className="min-h-11 rounded-lg border px-3 disabled:opacity-40">التالي</button></div></div>}
  </section>
}
