import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import toast from 'react-hot-toast'
import { supervisionService } from '../../services/supervision.service.js'

const input = 'min-h-11 w-full rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm outline-none focus:border-violet-500'
const label = { pending: 'لم يرد', acknowledged: 'اطلع', will_apply: 'سينفذ', applied: 'أبلغ بالتنفيذ', needs_discussion: 'يحتاج توضيحًا' }
const name = (person) => person ? `${person.firstNameAr || ''} ${person.lastNameAr || ''}`.trim() : '—'

function DirectiveRecipients({ directiveId, verify, onChanged }) {
  const [open, setOpen] = useState(false)
  const [page, setPage] = useState(1)
  const query = useQuery({ queryKey: ['academic-directive-recipients', directiveId, page],
    queryFn: () => supervisionService.academicDirectiveReceipts(directiveId, { page, limit: 20 }), enabled: open })
  return <div className="mt-3"><button onClick={() => setOpen(!open)} className="min-h-11 rounded-lg border border-violet-200 px-3 text-sm font-bold text-violet-700">{open ? 'إخفاء المستلمين' : 'عرض حالات المستلمين'}</button>
    {open && <div className="mt-2 space-y-2">{query.isLoading && <p className="text-sm">جارٍ التحميل...</p>}{query.isError && <p role="alert" className="text-sm text-red-700">تعذر تحميل المستلمين</p>}{(query.data?.data || []).map((receipt) => <div key={receipt._id} className="rounded-xl bg-gray-50 p-3 text-sm"><strong>{name(receipt.recipientId)}</strong><span className="mx-2 text-gray-500">{label[receipt.status]}</span>{receipt.verifiedAt && <span className="text-emerald-700">تم التحقق</span>}{receipt.reply && <p className="mt-1 text-xs text-gray-600">{receipt.reply}</p>}{receipt.status === 'applied' && !receipt.verifiedAt && <button disabled={verify.isPending} onClick={() => verify.mutate(receipt._id, { onSuccess: onChanged })} className="mt-2 min-h-11 rounded-lg border border-emerald-200 px-3 font-bold text-emerald-700">اعتماد التنفيذ</button>}</div>)}{!!query.data?.totalPages && <nav className="flex items-center gap-2 text-sm"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="min-h-11 rounded-lg border px-3 disabled:opacity-40">السابق</button><span>{page} من {query.data.totalPages}</span><button disabled={page >= query.data.totalPages} onClick={() => setPage(page + 1)} className="min-h-11 rounded-lg border px-3 disabled:opacity-40">التالي</button></nav>}</div>}
  </div>
}

export default function SupervisionAcademicDirectivesSection({ user }) {
  const leader = Boolean(user?.isPrimaryAdmin || user?.role === 'admin' || user?.supervisionPosition === 'manager')
  const qc = useQueryClient()
  const [page, setPage] = useState(1)
  const [form, setForm] = useState({ title: '', body: '', materialUrl: '', targetType: 'person', targetId: '', categoryKey: '' })
  const [personSearch, setPersonSearch] = useState('')
  const [replyDraft, setReplyDraft] = useState({})
  const query = useQuery({ queryKey: ['academic-directives', page], queryFn: () => supervisionService.academicDirectives({ page, limit: 20 }) })
  const people = useQuery({ queryKey: ['academic-directive-people', personSearch],
    queryFn: () => supervisionService.academicDirectiveRecipientsSearch(personSearch),
    enabled: Boolean(leader && form.targetType === 'person' && personSearch.trim().length >= 2) })
  const subjects = useQuery({ queryKey: ['supervision', 'subjects'], queryFn: supervisionService.subjects, enabled: Boolean(leader && form.targetType === 'category') })
  const error = (err) => toast.error(err.response?.data?.message || 'تعذر إتمام الطلب')
  const create = useMutation({ mutationFn: () => supervisionService.createAcademicDirective(form), onSuccess: () => { toast.success('أُرسل التوجيه'); setForm({ title: '', body: '', materialUrl: '', targetType: 'person', targetId: '', categoryKey: '' }); qc.invalidateQueries({ queryKey: ['academic-directives'] }) }, onError: error })
  const reply = useMutation({ mutationFn: ({ id, data }) => supervisionService.replyAcademicDirective(id, data), onSuccess: () => { toast.success('حُفظ ردك'); qc.invalidateQueries({ queryKey: ['academic-directives'] }) }, onError: error })
  const verify = useMutation({ mutationFn: (id) => supervisionService.verifyAcademicDirective(id), onSuccess: () => { toast.success('تم اعتماد التنفيذ'); qc.invalidateQueries({ queryKey: ['academic-directives'] }) }, onError: error })
  return <div className="space-y-5"><header className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold text-gray-900">التوجيهات الأكاديمية</h2><p className="mt-1 text-sm text-gray-500">لكل معلم أو مشرف مستلم حالة تنفيذ مستقلة؛ لا يُعد رد أحدهم تنفيذًا لباقي الفريق.</p></header>
    {leader && <form onSubmit={(e) => { e.preventDefault(); create.mutate() }} className="space-y-3 rounded-2xl border border-violet-100 bg-violet-50/50 p-5"><h3 className="font-bold">توجيه جديد</h3><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">العنوان<input required maxLength={160} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} className={input} /></label><label className="text-sm">إلى<select value={form.targetType} onChange={(e) => setForm({ ...form, targetType: e.target.value, targetId: '', categoryKey: '' })} className={input}><option value="person">شخص محدد</option><option value="category">فئة تدريس</option><option value="all">كل الفريق الأكاديمي</option></select></label></div>
      {form.targetType === 'person' && <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">بحث عن معلم أو مشرف<input value={personSearch} onChange={(e) => setPersonSearch(e.target.value)} className={input} placeholder="اكتب حرفين على الأقل" /></label><label className="text-sm">المستلم<select required value={form.targetId} onChange={(e) => setForm({ ...form, targetId: e.target.value })} className={input}><option value="">اختر المستلم</option>{(people.data || []).map((person) => <option key={person._id} value={person._id}>{name(person)} · {person.role === 'teacher' ? 'معلم' : 'مشرف'}</option>)}</select></label></div>}
      {form.targetType === 'category' && <label className="text-sm">الفئة<select required value={form.categoryKey} onChange={(e) => setForm({ ...form, categoryKey: e.target.value })} className={input}><option value="">اختر الفئة</option>{(subjects.data?.data || []).map((subject) => <option key={subject.key} value={subject.key}>{subject.nameAr}</option>)}</select></label>}
      <label className="block text-sm">التوجيه<textarea required maxLength={3000} rows={4} value={form.body} onChange={(e) => setForm({ ...form, body: e.target.value })} className={input} /></label><label className="block text-sm">رابط مادة مساعدة (اختياري)<input type="url" value={form.materialUrl} onChange={(e) => setForm({ ...form, materialUrl: e.target.value })} className={input} placeholder="https://" /></label><button disabled={create.isPending || form.targetType === 'person' && !form.targetId || form.targetType === 'category' && !form.categoryKey} className="min-h-11 rounded-xl bg-violet-700 px-5 font-bold text-white disabled:opacity-50">{create.isPending ? 'جارٍ الإرسال...' : 'إرسال التوجيه'}</button></form>}
    {query.isLoading && <p className="rounded-xl bg-white p-5 text-sm">جارٍ التحميل...</p>}{query.isError && <p role="alert" className="rounded-xl bg-red-50 p-5 text-sm text-red-700">تعذر تحميل التوجيهات <button onClick={() => query.refetch()} className="underline">إعادة المحاولة</button></p>}
    {!query.isLoading && !query.isError && !query.data?.data?.length && <p className="rounded-xl bg-white p-7 text-center text-sm text-gray-500">لا توجد توجيهات بعد</p>}
    {(query.data?.data || []).map((row) => leader ? <article key={row._id} className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-bold">{row.title}</h3><time className="text-xs text-gray-500">{new Date(row.createdAt).toLocaleString('ar-EG-u-nu-latn')}</time></div><p className="mt-2 whitespace-pre-wrap text-sm leading-7">{row.body}</p>{row.materialUrl && <a href={row.materialUrl} target="_blank" rel="noreferrer" className="text-sm text-violet-700 underline">المادة المرفقة</a>}<p className="mt-2 text-xs text-gray-500">{row.recipientCount} مستلم</p><p className="mt-2 text-xs text-gray-500">{Object.entries(row.statusCounts || {}).map(([status, count]) => `${label[status]}: ${count}`).join(" · ")}</p><DirectiveRecipients directiveId={row._id} verify={verify} onChanged={() => qc.invalidateQueries({ queryKey: ["academic-directive-recipients", row._id] })} /></article> : <article key={row._id} className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><h3 className="font-bold">{row.directiveId?.title}</h3><p className="mt-1 text-xs text-gray-500">{row.directiveId?.createdAt && new Date(row.directiveId.createdAt).toLocaleString('ar-EG-u-nu-latn')} · {label[row.status]}</p><p className="mt-3 whitespace-pre-wrap rounded-xl bg-violet-50 p-4 text-sm leading-7">{row.directiveId?.body}</p>{row.directiveId?.materialUrl && <a href={row.directiveId.materialUrl} target="_blank" rel="noreferrer" className="mt-2 inline-block text-sm text-violet-700 underline">مادة مساعدة</a>}{row.reply && <p className="mt-2 text-xs text-gray-600">ردك: {row.reply}</p>}<form onSubmit={(e) => { e.preventDefault(); const draft = replyDraft[row._id] || { status: 'acknowledged', reply: '' }; reply.mutate({ id: row._id, data: draft }) }} className="mt-3 grid gap-2 sm:grid-cols-[180px_1fr_auto]"><select aria-label="حالة التنفيذ" value={replyDraft[row._id]?.status || 'acknowledged'} onChange={(e) => setReplyDraft({ ...replyDraft, [row._id]: { ...replyDraft[row._id], status: e.target.value } })} className={input}><option value="acknowledged">اطلعت</option><option value="will_apply">سأطبق</option><option value="applied">تم التنفيذ</option><option value="needs_discussion">أحتاج توضيحًا</option></select><input aria-label="ردك" maxLength={2000} required={replyDraft[row._id]?.status === 'needs_discussion'} value={replyDraft[row._id]?.reply || ''} onChange={(e) => setReplyDraft({ ...replyDraft, [row._id]: { ...replyDraft[row._id], reply: e.target.value } })} className={input} placeholder="رد مختصر" /><button disabled={reply.isPending} className="min-h-11 rounded-xl bg-violet-700 px-4 font-bold text-white">إرسال</button></form></article>)}
    {!!query.data?.totalPages && <nav aria-label="صفحات التوجيهات" className="flex items-center gap-2 text-sm"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="min-h-11 rounded-lg border px-3 disabled:opacity-40">السابق</button><span>{page} من {query.data.totalPages}</span><button disabled={page >= query.data.totalPages} onClick={() => setPage(page + 1)} className="min-h-11 rounded-lg border px-3 disabled:opacity-40">التالي</button></nav>}
  </div>
}
