import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { ClipboardCheck, UsersRound } from 'lucide-react'
import { supervisionService } from '../../services/supervision.service.js'

const name = (person) => [person?.firstNameAr, person?.lastNameAr].filter(Boolean).join(' ') || '—'
const date = (value) => value ? new Date(value).toLocaleDateString('ar-EG-u-nu-latn') : '—'
const teamName = (team) => team === 'academic' ? 'الأكاديمي' : 'الإداري'
const route = (team) => `/admin/supervision/${team === 'academic' ? 'academic-manager' : 'administrative-manager'}?view=assignments`

export default function SupervisionProfileCard({ kind, id, full = false }) {
  const query = useQuery({ queryKey: ['supervision', 'profile', kind, id], queryFn: () => kind === 'teacher' ? supervisionService.teacherProfile(id) : supervisionService.studentProfile(id), enabled: !!id })
  const data = query.data
  const assignments = kind === 'teacher' ? data?.assignments || [] : data?.owners || []
  const rows = kind === 'teacher' && !full ? assignments.filter((row) => row.scopeType !== 'student') : assignments
  return <section dir="rtl" className="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm" aria-label="بيانات الإشراف">
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-50 text-violet-700"><UsersRound size={19} aria-hidden="true" /></span><div><h2 className="font-heading text-base font-extrabold text-gray-950">الإشراف المسؤول</h2><p className="text-xs text-gray-600">تكليفات الفريق المؤرخة حسب بيانات المنصة</p></div></div><div className="flex flex-wrap gap-2"><Link to={route('academic')} className="min-h-11 rounded-xl border border-violet-200 px-4 py-2 text-sm font-bold text-violet-700 no-underline hover:bg-violet-50">إدارة الأكاديمي</Link><Link to={route('administrative')} className="min-h-11 rounded-xl border border-gray-200 px-4 py-2 text-sm font-bold text-gray-700 no-underline hover:bg-gray-50">إدارة الإداري</Link></div></div>
    {query.isLoading && <p className="mt-4 text-sm text-gray-600">جارٍ تحميل بيانات الإشراف...</p>}
    {query.isError && <p role="alert" className="mt-4 text-sm text-red-700">تعذّر تحميل بيانات الإشراف. <button type="button" onClick={() => query.refetch()} className="underline">إعادة المحاولة</button></p>}
    {data && !rows.length && <p className="mt-4 rounded-xl bg-gray-50 p-4 text-sm text-gray-600">لا يوجد مشرف محدد في التكليفات الحالية.</p>}
    {!!rows.length && <div className="mt-4 grid gap-3 sm:grid-cols-2">{rows.map((row) => <div key={`${row.team}:${row.cohortId || row.teacher?._id || row.studentId?._id || row.supervisorId?._id}:${row.startsAt}`} className="rounded-xl border border-gray-100 bg-gray-50/70 p-3"><p className="text-xs font-bold text-violet-700">الإشراف {teamName(row.team)} {row.scopeType === 'student' ? '· تكليف خاص' : row.scopeType === 'cohort' ? '· مجموعة' : ''}</p><p className="mt-1 text-sm font-bold text-gray-950">{name(row.supervisorId)}</p>{row.teacher && <p className="mt-1 text-xs text-gray-600">مع المعلم {name(row.teacher)}</p>}{row.studentId && <p className="mt-1 text-xs text-gray-600">للطالب {name(row.studentId)}</p>}{row.cohortName && <p className="mt-1 text-xs text-gray-600">{row.cohortName} · {row.studentCount} طالب من طلاب المعلم</p>}<p className="mt-1 text-xs text-gray-500">من {date(row.startsAt)}</p></div>)}</div>}
    {kind === 'teacher' && !full && (data?.assignments || []).some((row) => row.scopeType === 'student') && <p className="mt-3 text-xs text-gray-600">يوجد تكليف خاص لبعض الطلاب؛ يظهر في سجل الإشراف التفصيلي.</p>}
    {kind === 'student' && data?.memberships?.length > 0 && <div className="mt-4 border-t border-gray-100 pt-4"><h3 className="text-sm font-bold text-gray-900">مجموعات الطالب</h3><p className="mt-2 text-sm text-gray-600">{data.memberships.map((row) => `${row.cohortId?.name || 'مجموعة'} (${teamName(row.team)})`).join('، ')}</p></div>}
    {full && <div className="mt-5 space-y-4 border-t border-gray-100 pt-5"><h3 className="flex items-center gap-2 text-sm font-extrabold text-gray-950"><ClipboardCheck size={17} className="text-violet-700" /> سجل المتابعة الأكاديمية</h3>{!data?.reports?.length ? <p className="text-sm text-gray-600">لا توجد تقارير متابعة R1 بعد.</p> : <div className="space-y-2">{data.reports.map((report) => <article key={report._id} className="rounded-xl border border-gray-100 p-3 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-gray-950">{date(report.scheduledAt)} · {name(report.supervisorId)}</strong><span className="rounded-full bg-violet-50 px-2 py-1 text-xs font-bold text-violet-700">{report.status === 'reviewed' ? 'تمت المراجعة' : report.status === 'submitted' ? 'بانتظار المراجعة' : 'قيد الإعداد'}</span></div>{report.teacherPerformance && <p className="mt-2 text-gray-700">أداء المعلم: {report.teacherPerformance}</p>}{report.studentLevel && <p className="mt-2 text-gray-700">مستوى الطالب: {report.studentLevel}</p>}{report.observations && <p className="mt-2 text-gray-700">الملاحظات: {report.observations}</p>}</article>)}</div>}
      {kind === 'student' && <div><h3 className="text-sm font-extrabold text-gray-950">الخطة والمنهج</h3>{!data?.plans?.length ? <p className="mt-2 text-sm text-gray-600">لا توجد خطة أكاديمية بعد.</p> : <div className="mt-2 space-y-2">{data.plans.map((plan) => <div key={plan._id} className="rounded-xl border border-gray-100 p-3 text-sm"><strong>{plan.courseId?.nameAr || plan.subjectKey}</strong><p className="mt-1 text-gray-600">{plan.milestones?.filter((step) => step.status === 'completed').length || 0} من {plan.milestones?.length || 0} مراحل مكتملة · {plan.status}</p></div>)}</div>}</div>}
    </div>}
  </section>
}
