import { useEffect, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import toast from 'react-hot-toast'
import { AlertTriangle, CalendarClock, CheckCircle2, CircleDollarSign } from 'lucide-react'
import { supervisionService } from '../../services/supervision.service.js'

const input = 'min-h-11 w-full rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm text-gray-900 outline-none focus:border-violet-500 focus:ring-2 focus:ring-violet-100'
const types = [['student_apology', 'اعتذار الطالب'], ['teacher_apology', 'اعتذار المعلم'], ['student_absence', 'غياب الطالب'], ['teacher_absence', 'غياب المعلم'], ['delay', 'تأخير'], ['postpone', 'تأجيل'], ['advance', 'تقديم الموعد'], ['reschedule', 'تغيير الموعد'], ['link_issue', 'مشكلة الرابط'], ['substitute', 'معلم بديل'], ['compensation', 'تعويض'], ['other', 'حالة أخرى']]
const actions = [['reschedule', 'تغيير الموعد'], ['cancel', 'إلغاء الحصة'], ['substitute', 'تعيين معلم بديل'], ['update_link', 'تحديث الرابط'], ['report_delay', 'تسجيل تأخير'], ['grant_compensation', 'إضافة حصة تعويضية للرصيد'], ['schedule_makeup', 'جدولة حصة تعويضية']]
const fullName = (person) => [person?.firstNameAr, person?.lastNameAr].filter(Boolean).join(' ') || '—'
const localDateTime = (value) => new Date(value).toLocaleString('ar-EG', { dateStyle: 'medium', timeStyle: 'short' })
const localInput = (value) => { const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16) }
const tomorrow = () => localInput(Date.now() + 86400000)
const today = () => localInput(Date.now()).slice(0, 10)
const dayRange = (day) => { const start = new Date(`${day}T00:00:00`); return { from: start.toISOString(), to: new Date(start.getTime() + 86400000).toISOString() } }

function Field({ label, children }) { return <label className="block text-sm font-semibold text-gray-700">{label}{children}</label> }
function Notice({ children }) { return <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{children}</p> }

export default function SupervisionExceptionsSection({ team, user, selectedSessionId }) {
  const qc = useQueryClient()
  const isAdmin = !!(user?.isPrimaryAdmin || user?.role === 'admin')
  const adminCanManage = !!(isAdmin && (user?.isPrimaryAdmin || user?.permissions?.includes('supervision.manage')))
  const canOperate = Boolean(adminCanManage || (team === 'administrative' && user?.supervisionTeam === team))
  const canDecide = Boolean(adminCanManage || (user?.supervisionTeam === 'administrative' && user?.supervisionPosition === 'manager'))
  const [status, setStatus] = useState('open')
  const [page, setPage] = useState(1)
  const [day, setDay] = useState(today)
  const [sessionPage, setSessionPage] = useState(1)
  const [requestPage, setRequestPage] = useState(1)
  const [showCreate, setShowCreate] = useState(!!selectedSessionId)
  const [form, setForm] = useState({ sessionId: selectedSessionId || '', type: 'student_apology', reason: '', ownerId: user?.supervisionTeam === 'administrative' ? user._id : '', followUpAt: tomorrow() })
  const [ownerSearch, setOwnerSearch] = useState('')
  const [activeId, setActiveId] = useState(null)
  const [action, setAction] = useState('reschedule')
  const [payload, setPayload] = useState({})
  const [resolution, setResolution] = useState('')
  const [adjustFor, setAdjustFor] = useState(null)
  const [adjustForm, setAdjustForm] = useState({ accountType: 'teacher_payroll', amount: '', reason: '' })
  const [decisionFor, setDecisionFor] = useState(null)
  const [decision, setDecision] = useState({ decision: 'approve', amount: '', reason: '' })
  const [reassignFor, setReassignFor] = useState(null)
  const [reassign, setReassign] = useState({ ownerId: '', followUpAt: tomorrow() })

  useEffect(() => { if (selectedSessionId) { setForm((old) => ({ ...old, sessionId: selectedSessionId })); setShowCreate(true) } }, [selectedSessionId])
  const cases = useQuery({ queryKey: ['supervision', 'exceptions', team, status, page], queryFn: () => supervisionService.exceptions({ team, status, page, limit: 20 }), refetchInterval: 30000 })
  const requests = useQuery({ queryKey: ['supervision', 'adjustment-requests', team, requestPage], queryFn: () => supervisionService.adjustmentRequests({ page: requestPage, limit: 20 }), enabled: team === 'administrative', refetchInterval: 30000 })
  const sessions = useQuery({ queryKey: ['supervision', 'exception-sessions', day, sessionPage], queryFn: () => supervisionService.dailySessions({ team: 'administrative', ...dayRange(day), page: sessionPage, limit: 50 }), enabled: Boolean(canOperate && showCreate) })
  const owners = useQuery({ queryKey: ['supervision', 'exception-owners', ownerSearch], queryFn: () => supervisionService.people({ team: 'administrative', active: true, search: ownerSearch, limit: 50 }), enabled: Boolean(canOperate && (showCreate || !!reassignFor)) })
  const teachers = useQuery({ queryKey: ['supervision', 'exception-teachers'], queryFn: () => supervisionService.teachers({ limit: 50 }), enabled: Boolean(canOperate && activeId && (action === 'substitute' || action === 'schedule_makeup')) })
  const refresh = () => qc.invalidateQueries({ queryKey: ['supervision'] })
  const onError = (error) => toast.error(error.response?.data?.message || 'تعذّر تنفيذ الإجراء')
  const create = useMutation({ mutationFn: () => supervisionService.createException({ ...form, followUpAt: new Date(form.followUpAt).toISOString() }), onSuccess: () => { toast.success('تم تسجيل الحالة'); setShowCreate(false); setForm((old) => ({ ...old, reason: '' })); refresh() }, onError })
  const apply = useMutation({ mutationFn: () => supervisionService.applyException(activeId, { action, payload: { ...payload, ...(payload.newDate ? { newDate: new Date(payload.newDate).toISOString() } : {}), ...(payload.scheduledAt ? { scheduledAt: new Date(payload.scheduledAt).toISOString() } : {}) } }), onSuccess: () => { toast.success('تم تنفيذ الإجراء'); setActiveId(null); setPayload({}); refresh() }, onError })
  const retryCase = useMutation({ mutationFn: (id) => supervisionService.retryException(id), onSuccess: () => { toast.success('اكتمل الإجراء'); refresh() }, onError })
  const resolve = useMutation({ mutationFn: (id) => supervisionService.resolveException(id, resolution), onSuccess: () => { toast.success('تم إغلاق الحالة'); setActiveId(null); setResolution(''); refresh() }, onError })
  const transfer = useMutation({ mutationFn: () => supervisionService.reassignException(reassignFor, { ownerId: reassign.ownerId, followUpAt: new Date(reassign.followUpAt).toISOString() }), onSuccess: () => { toast.success('انتقلت المتابعة للمسؤول الجديد'); setReassignFor(null); refresh() }, onError })
  const request = useMutation({ mutationFn: () => supervisionService.requestAdjustment({ sessionId: rows.find((row) => row._id === adjustFor)?.sessionId?._id, accountType: adjustForm.accountType, amount: Number(adjustForm.amount), reason: adjustForm.reason }), onSuccess: () => { toast.success('رُفع الطلب للمدير دون خصم الآن'); setAdjustFor(null); setAdjustForm({ accountType: 'teacher_payroll', amount: '', reason: '' }); refresh() }, onError })
  const decide = useMutation({ mutationFn: () => supervisionService.decideAdjustment(decisionFor, { decision: decision.decision, amount: decision.decision === 'reject' ? undefined : Number(decision.amount), reason: decision.reason }), onSuccess: () => { toast.success('تم تسجيل القرار'); setDecisionFor(null); refresh() }, onError })
  const retry = useMutation({ mutationFn: (id) => supervisionService.retryAdjustment(id), onSuccess: () => { toast.success('اكتمل القرار'); refresh() }, onError })
  const rows = cases.data?.data || []
  const people = [...new Map([...(user?.supervisionTeam === 'administrative' ? [user] : []), ...(owners.data?.data || [])].filter((person) => person.supervisionTeam === 'administrative').map((person) => [person._id, person])).values()]

  return <section className="space-y-5" aria-label="الحالات والتعويضات">
    <div className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="inline-flex rounded-xl bg-amber-50 p-2 text-amber-700"><AlertTriangle size={20} /></span><h2 className="mt-2 font-heading text-xl font-bold text-gray-900">الاستثناءات والتعويضات</h2><p className="mt-1 text-sm text-gray-500">كل حالة لها مسؤول وموعد متابعة. تغيير الحصة ينعكس على جدول الطالب والمعلم، والخصم لا يُطبق قبل قرار المدير.</p></div>{canOperate && <button type="button" onClick={() => setShowCreate(!showCreate)} className="min-h-11 rounded-xl bg-violet-600 px-4 text-sm font-bold text-white">{showCreate ? 'إخفاء النموذج' : 'تسجيل حالة'}</button>}</div></div>
    {canOperate && showCreate && <form onSubmit={(event) => { event.preventDefault(); create.mutate() }} className="grid gap-3 rounded-2xl border border-violet-100 bg-white p-5 shadow-sm sm:grid-cols-2">
      <Field label="يوم الحصة"><input type="date" value={day} onChange={(event) => { setDay(event.target.value); setSessionPage(1) }} className={`mt-1 ${input}`} /></Field>
      <Field label="الحصة"><select required value={form.sessionId} onChange={(event) => setForm({ ...form, sessionId: event.target.value })} className={`mt-1 ${input}`}><option value="">اختر الحصة</option>{selectedSessionId && !(sessions.data?.data || []).some((row) => row._id === selectedSessionId) && <option value={selectedSessionId}>الحصة المحددة من قائمة اليوم</option>}{(sessions.data?.data || []).map((row) => <option key={row._id} value={row._id}>{row.titleAr} · {localDateTime(row.scheduledAt)}</option>)}</select></Field>
      <div className="flex items-center justify-between text-xs text-gray-500 sm:col-span-2"><span>{sessions.isError ? 'تعذّر تحميل الحصص' : `${sessions.data?.total || 0} حصة في هذا اليوم`}</span><span><button type="button" disabled={sessionPage <= 1} onClick={() => setSessionPage(sessionPage - 1)} className="ml-3 font-bold text-violet-700 disabled:opacity-40">السابق</button><button type="button" disabled={!sessions.data?.hasMore} onClick={() => setSessionPage(sessionPage + 1)} className="font-bold text-violet-700 disabled:opacity-40">التالي</button></span></div>
      <Field label="نوع الحالة"><select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })} className={`mt-1 ${input}`}>{types.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field>
      <Field label="موعد المتابعة"><input required type="datetime-local" value={form.followUpAt} onChange={(event) => setForm({ ...form, followUpAt: event.target.value })} className={`mt-1 ${input}`} /></Field>
      <Field label="بحث عن المسؤول"><input value={ownerSearch} onChange={(event) => setOwnerSearch(event.target.value)} className={`mt-1 ${input}`} placeholder="الاسم أو البريد" /></Field>
      <Field label="المسؤول"><select required value={form.ownerId} onChange={(event) => setForm({ ...form, ownerId: event.target.value })} className={`mt-1 ${input}`}><option value="">اختر المسؤول</option>{people.map((person) => <option key={person._id} value={person._id}>{fullName(person)} · {person.supervisionPosition === 'manager' ? 'مدير' : 'مشرف'}</option>)}</select></Field>
      <Field label="السبب والتفاصيل"><textarea required maxLength={1000} value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} rows={2} className={`mt-1 ${input}`} /></Field>
      <button disabled={create.isPending || !form.sessionId || !form.ownerId} className="min-h-11 self-end rounded-xl bg-violet-600 px-5 font-bold text-white disabled:opacity-50">حفظ الحالة</button>
    </form>}
    <div className="flex flex-wrap gap-2">{[['open', 'الحالات المفتوحة'], ['resolved', 'الحالات المغلقة']].map(([value, label]) => <button key={value} type="button" onClick={() => { setStatus(value); setPage(1) }} className={`min-h-11 rounded-xl px-4 text-sm font-bold ${status === value ? 'bg-violet-600 text-white' : 'border border-gray-200 bg-white text-gray-700'}`}>{label}</button>)}</div>
    {cases.isLoading && <p className="rounded-xl bg-white p-5 text-sm text-gray-500">جارٍ تحميل الحالات...</p>}
    {cases.isError && <Notice>تعذّر تحميل الحالات. <button type="button" onClick={() => cases.refetch()} className="font-bold underline">إعادة المحاولة</button></Notice>}
    {!cases.isLoading && !cases.isError && !rows.length && <p className="rounded-xl bg-white p-8 text-center text-sm text-gray-500">لا توجد حالات في هذا القسم.</p>}
    {rows.map((row) => <article key={row._id} className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold text-violet-700">{types.find(([value]) => value === row.type)?.[1] || row.type} · {row.sessionId?.titleAr || 'حصة'}</p><h3 className="mt-2 font-bold text-gray-900">{row.reason}</h3><p className="mt-2 text-sm text-gray-600">المسؤول: {fullName(row.ownerId)} · المتابعة: {localDateTime(row.followUpAt)}</p><p className="mt-1 text-xs text-gray-500">{row.actionState === 'applied' ? `الإجراء المنفذ: ${actions.find(([value]) => value === row.action)?.[1] || row.action}` : row.actionState === 'failed' ? `تعذّر الإجراء: ${row.actionError || 'أعد المحاولة'}` : 'لم ينفذ إجراء بعد'}{row.makeupSessionId ? ` · التعويض: ${row.makeupSessionId.status === 'completed' ? 'اكتمل' : 'قيد التنفيذ'}` : ''}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${row.status === 'resolved' ? 'bg-emerald-50 text-emerald-700' : new Date(row.followUpAt) < new Date() ? 'bg-red-50 text-red-700' : 'bg-amber-50 text-amber-800'}`}>{row.status === 'resolved' ? 'مغلقة' : new Date(row.followUpAt) < new Date() ? 'متأخرة' : 'مفتوحة'}</span></div>
      {canOperate && row.status === 'open' && <div className="mt-4 flex flex-wrap gap-2 border-t border-gray-100 pt-4"><button type="button" onClick={() => { setActiveId(activeId === row._id ? null : row._id); setAction('reschedule'); setPayload({}); setResolution('') }} className="min-h-11 rounded-xl border border-violet-200 px-3 text-sm font-bold text-violet-700">إجراء / إغلاق</button>{['failed', 'processing'].includes(row.actionState) && <button type="button" disabled={retryCase.isPending} onClick={() => retryCase.mutate(row._id)} className="min-h-11 rounded-xl border border-red-200 px-3 text-sm font-bold text-red-700 disabled:opacity-50">استكمال الإجراء المعلّق</button>}{canDecide && <button type="button" onClick={() => { setReassignFor(reassignFor === row._id ? null : row._id); setReassign({ ownerId: row.ownerId?._id || '', followUpAt: tomorrow() }) }} className="min-h-11 rounded-xl border border-gray-200 px-3 text-sm font-bold text-gray-700">نقل للشيفت التالي</button>}{team === 'administrative' && <button type="button" onClick={() => setAdjustFor(adjustFor === row._id ? null : row._id)} className="min-h-11 rounded-xl border border-amber-200 px-3 text-sm font-bold text-amber-800">طلب خصم</button>}</div>}
      {activeId === row._id && canOperate && <div className="mt-4 space-y-4 rounded-xl bg-violet-50/60 p-4">{row.actionState === 'none' && <form onSubmit={(event) => { event.preventDefault(); apply.mutate() }} className="grid gap-3 sm:grid-cols-2"><Field label="الإجراء"><select value={action} onChange={(event) => { setAction(event.target.value); setPayload({}) }} className={`mt-1 ${input}`}>{actions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field>
        {action === 'reschedule' && <Field label="الموعد الجديد"><input required disabled={row.actionState === 'failed'} type="datetime-local" value={payload.newDate || ''} onChange={(event) => setPayload({ ...payload, newDate: event.target.value })} className={`mt-1 ${input}`} /></Field>}
        {action === 'cancel' && <Field label="الاعتذار أو الإلغاء من طرف"><select disabled={row.actionState === 'failed'} value={payload.cancelledByRole || 'student'} onChange={(event) => setPayload({ ...payload, cancelledByRole: event.target.value })} className={`mt-1 ${input}`}><option value="student">الطالب</option><option value="teacher">المعلم</option><option value="admin">الأكاديمية</option></select></Field>}
        {(action === 'substitute' || action === 'schedule_makeup') && <Field label="المعلم"><select required disabled={row.actionState === 'failed'} value={payload.teacherId || ''} onChange={(event) => setPayload({ ...payload, teacherId: event.target.value })} className={`mt-1 ${input}`}><option value="">اختر المعلم</option>{(teachers.data?.data || []).map((teacher) => <option key={teacher._id} value={teacher._id}>{fullName(teacher)}</option>)}</select></Field>}
        {action === 'schedule_makeup' && <Field label="موعد التعويض"><input required disabled={row.actionState === 'failed'} type="datetime-local" value={payload.scheduledAt || ''} onChange={(event) => setPayload({ ...payload, scheduledAt: event.target.value })} className={`mt-1 ${input}`} /></Field>}
        {action === 'update_link' && <Field label="رابط الاجتماع"><input required disabled={row.actionState === 'failed'} type="url" value={payload.meetingLink || ''} onChange={(event) => setPayload({ ...payload, meetingLink: event.target.value })} className={`mt-1 ${input}`} placeholder="https://" /></Field>}
        {action === 'report_delay' && <><Field label="مدة التأخير بالدقائق"><input required disabled={row.actionState === 'failed'} type="number" min="1" max="240" value={payload.minutes || ''} onChange={(event) => setPayload({ ...payload, minutes: Number(event.target.value) })} className={`mt-1 ${input}`} /></Field><Field label="سبب التأخير"><select disabled={row.actionState === 'failed'} value={payload.reasonCode || 'other'} onChange={(event) => setPayload({ ...payload, reasonCode: event.target.value })} className={`mt-1 ${input}`}><option value="teacher_delay">المعلم</option><option value="student_delay">الطالب</option><option value="technical_issue">تقني</option><option value="emergency">طارئ</option><option value="other">آخر</option></select></Field></>}
        <button disabled={apply.isPending} className="min-h-11 self-end rounded-xl bg-violet-600 px-4 font-bold text-white disabled:opacity-50">تنفيذ الإجراء</button></form>}
        {row.actionState !== 'processing' && <form onSubmit={(event) => { event.preventDefault(); resolve.mutate(row._id) }} className="flex flex-wrap gap-2 border-t border-violet-100 pt-3"><input required maxLength={1000} value={resolution} onChange={(event) => setResolution(event.target.value)} className={`${input} flex-1`} placeholder="نتيجة المتابعة قبل الإغلاق" /><button disabled={resolve.isPending || !resolution.trim() || row.actionState === 'failed' || !!row.makeupSessionId && row.makeupSessionId.status !== 'completed'} className="min-h-11 rounded-xl bg-emerald-700 px-4 font-bold text-white disabled:opacity-50"><CheckCircle2 size={16} className="ml-1 inline" /> إغلاق الحالة</button></form>}</div>}
      {reassignFor === row._id && canDecide && <form onSubmit={(event) => { event.preventDefault(); transfer.mutate() }} className="mt-3 grid gap-3 rounded-xl bg-gray-50 p-4 sm:grid-cols-3"><Field label="المسؤول الجديد"><select required value={reassign.ownerId} onChange={(event) => setReassign({ ...reassign, ownerId: event.target.value })} className={`mt-1 ${input}`}>{people.map((person) => <option key={person._id} value={person._id}>{fullName(person)}</option>)}</select></Field><Field label="موعد المتابعة"><input required type="datetime-local" value={reassign.followUpAt} onChange={(event) => setReassign({ ...reassign, followUpAt: event.target.value })} className={`mt-1 ${input}`} /></Field><button disabled={transfer.isPending} className="min-h-11 self-end rounded-xl bg-violet-600 px-4 font-bold text-white disabled:opacity-50">نقل المسؤولية</button></form>}
      {adjustFor === row._id && team === 'administrative' && canOperate && <form onSubmit={(event) => { event.preventDefault(); request.mutate() }} className="mt-3 grid gap-3 rounded-xl bg-amber-50 p-4 sm:grid-cols-2"><Field label="الحساب"><select value={adjustForm.accountType} onChange={(event) => setAdjustForm({ ...adjustForm, accountType: event.target.value, amount: '' })} className={`mt-1 ${input}`}><option value="teacher_payroll">مستحقات المعلم بالجنيه</option><option value="student_lessons">رصيد الطالب بالحصص</option></select></Field><Field label="القيمة المقترحة"><input required type="number" min={adjustForm.accountType === 'student_lessons' ? '1' : '0.01'} step={adjustForm.accountType === 'student_lessons' ? '1' : '0.01'} value={adjustForm.amount} onChange={(event) => setAdjustForm({ ...adjustForm, amount: event.target.value })} className={`mt-1 ${input}`} /></Field><Field label="السبب"><input required maxLength={1000} value={adjustForm.reason} onChange={(event) => setAdjustForm({ ...adjustForm, reason: event.target.value })} className={`mt-1 ${input}`} /></Field><button disabled={request.isPending} className="min-h-11 self-end rounded-xl bg-amber-700 px-4 font-bold text-white disabled:opacity-50">إرسال الطلب للمدير</button></form>}
    </article>)}
    {!!cases.data?.total && <div className="flex items-center justify-between rounded-xl bg-white px-4 py-3 text-sm text-gray-600"><span>{cases.data.total} حالة · صفحة {page}</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="min-h-11 rounded-lg border px-3 disabled:opacity-40">السابق</button><button disabled={!cases.data.hasMore} onClick={() => setPage(page + 1)} className="min-h-11 rounded-lg border px-3 disabled:opacity-40">التالي</button></div></div>}
    {team === 'administrative' && <div className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><CircleDollarSign className="text-violet-700" size={21} /><div><h3 className="font-heading text-lg font-bold text-gray-900">طلبات الخصم والقرار</h3><p className="text-xs text-gray-500">الطلب وحده لا يغير رصيد الطالب أو مستحقات المعلم.</p></div></div>{requests.isError && <Notice>تعذّر تحميل طلبات الخصم.</Notice>}{requests.isLoading && <p className="text-sm text-gray-500">جارٍ تحميل الطلبات...</p>}{!requests.isLoading && !requests.isError && !(requests.data?.data || []).length && <p className="text-sm text-gray-500">لا توجد طلبات.</p>}
      <div className="space-y-3">{(requests.data?.data || []).map((row) => <article key={row._id} className="rounded-xl border border-gray-100 p-4"><div className="flex flex-wrap justify-between gap-2"><div><p className="font-bold text-gray-900">{row.reason}</p><p className="mt-1 text-sm text-gray-600">{fullName(row.accountOwnerId)} · {row.requestedAmount} {row.unit === 'lesson' ? 'حصة' : 'جنيه'} · {row.accountType === 'teacher_payroll' ? 'مستحقات المعلم' : 'رصيد الطالب'}</p><p className="mt-1 text-xs text-gray-500">طلبه {fullName(row.requestedBy)} · {localDateTime(row.createdAt)}</p></div><span className="text-sm font-bold text-violet-700">{row.status === 'pending' ? 'ينتظر القرار' : row.status === 'processing' ? 'قرار قيد التنفيذ' : row.status === 'rejected' ? 'مرفوض' : row.status === 'bonus' ? 'مكافأة' : 'خصم معتمد'}</span></div>
        {canDecide && row.status === 'pending' && <button type="button" onClick={() => { setDecisionFor(row._id); setDecision({ decision: 'approve', amount: String(row.requestedAmount), reason: '' }) }} className="mt-3 min-h-11 rounded-xl border border-violet-200 px-3 text-sm font-bold text-violet-700">اتخاذ قرار</button>}
        {canDecide && row.status === 'processing' && <button type="button" disabled={retry.isPending} onClick={() => retry.mutate(row._id)} className="mt-3 min-h-11 rounded-xl border border-amber-200 px-3 text-sm font-bold text-amber-800">استكمال القرار المعلّق</button>}
        {decisionFor === row._id && <form onSubmit={(event) => { event.preventDefault(); decide.mutate() }} className="mt-3 grid gap-3 rounded-xl bg-violet-50 p-4 sm:grid-cols-2"><Field label="القرار"><select value={decision.decision} onChange={(event) => setDecision({ ...decision, decision: event.target.value })} className={`mt-1 ${input}`}><option value="approve">اعتماد الخصم</option><option value="reject">رفض</option><option value="bonus">تحويل إلى مكافأة</option></select></Field>{decision.decision !== 'reject' && <Field label="القيمة المعتمدة"><input required type="number" min={row.unit === 'lesson' ? '1' : '0.01'} step={row.unit === 'lesson' ? '1' : '0.01'} value={decision.amount} onChange={(event) => setDecision({ ...decision, amount: event.target.value })} className={`mt-1 ${input}`} /></Field>}<Field label="سبب القرار"><input required maxLength={1000} value={decision.reason} onChange={(event) => setDecision({ ...decision, reason: event.target.value })} className={`mt-1 ${input}`} /></Field><button disabled={decide.isPending} className="min-h-11 self-end rounded-xl bg-violet-600 px-4 font-bold text-white disabled:opacity-50">تأكيد القرار</button></form>}</article>)}</div>
      {!!requests.data?.total && <div className="mt-4 flex items-center justify-between text-sm text-gray-600"><span>{requests.data.total} طلب · صفحة {requestPage}</span><div className="flex gap-2"><button disabled={requestPage <= 1} onClick={() => setRequestPage(requestPage - 1)} className="min-h-11 rounded-lg border px-3 disabled:opacity-40">السابق</button><button disabled={!requests.data.hasMore} onClick={() => setRequestPage(requestPage + 1)} className="min-h-11 rounded-lg border px-3 disabled:opacity-40">التالي</button></div></div>}
    </div>}
    <p className="text-xs text-gray-500"><CalendarClock size={14} className="ml-1 inline" /> الحالات المفتوحة والمتأخرة تبقى ظاهرة للشيفت التالي حتى تُنقل لمسؤول جديد أو تُغلق بسبب واضح.</p>
  </section>
}
