import { useEffect, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import toast from 'react-hot-toast'
import { ClipboardCheck, Clock3, FileText, UsersRound } from 'lucide-react'
import { supervisionService } from '../../services/supervision.service.js'

const name = (person) => `${person?.firstNameAr || ''} ${person?.lastNameAr || ''}`.trim() || '—'
const date = (value) => value ? new Date(value).toLocaleString('en-GB', { dateStyle: 'short', timeStyle: 'short' }) : '—'
const stateLabel = { submitted: 'تم التسليم', missing: 'لم يسلّم', pending: 'لم يحن الموعد', on_time: 'تقرير في الموعد', late: 'متأخر', late_missing: 'تقرير متأخر ومفقود', within_grace: 'مهلة التقرير جارية' }
const box = 'rounded-2xl border border-gray-100 bg-white p-4 shadow-sm'
const button = 'min-h-11 rounded-xl bg-violet-700 px-4 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-50'
const input = 'w-full min-h-11 rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm text-gray-900 outline-none focus:border-violet-600'

export default function SupervisionHandoffSection({ team, user, onOpenException }) {
  const qc = useQueryClient()
  const [page, setPage] = useState(1)
  const [selection, setSelection] = useState(null)
  const [note, setNote] = useState('')
  const [analysis, setAnalysis] = useState('')
  const manager = user?.isPrimaryAdmin || user?.role === 'admin' || user?.supervisionPosition === 'manager'
  const records = useQuery({ queryKey: ['supervision', 'shift-records', team, page], queryFn: () => supervisionService.shiftRecords({ team, page, limit: 10 }) })
  const feed = useQuery({ queryKey: ['supervision', 'shift-handoffs', team], queryFn: () => supervisionService.shiftHandoffs(team) })
  const detail = useQuery({ queryKey: ['supervision', 'shift-record', team, selection?.shiftId, selection?.memberId],
    queryFn: () => supervisionService.shiftRecord(selection.shiftId, selection.memberId), enabled: !!selection })
  const refresh = () => qc.invalidateQueries({ queryKey: ['supervision'] })
  const action = useMutation({ mutationFn: async ({ kind, shiftId, value }) => {
    if (kind === 'in') return supervisionService.checkInShift(shiftId)
    if (kind === 'out') return supervisionService.checkOutShift(shiftId)
    if (kind === 'handoff') return supervisionService.handoffShift(shiftId, value)
    if (kind === 'draft') return supervisionService.saveShiftReportDraft(shiftId, value)
    return supervisionService.submitShiftReport(shiftId, value)
  }, onSuccess: (_, variables) => { toast.success('تم الحفظ'); if (variables.kind === 'handoff') setNote(''); if (variables.kind === 'report') setAnalysis(''); refresh() },
  onError: (error) => toast.error(error.response?.data?.message || 'تعذّر حفظ الإجراء') })
  const chosen = detail.data
  const myRecord = chosen && String(chosen.member?._id) === String(user?._id)
  const now = Date.now()
  useEffect(() => { setAnalysis(detail.data?.record?.analysis || '') }, [detail.data?.record?.analysis, selection?.shiftId, selection?.memberId])
  const submitted = chosen?.record?.reportSnapshot
  const sourceChanged = submitted && [...['total', 'completed', 'studentPresent', 'studentAbsent', 'apologies', 'absences'], ...(chosen?.shift?.team === 'academic' && submitted.observedLessons !== null && submitted.observedLessons !== undefined ? ['observedLessons', 'observedReportsSubmitted', 'observedEvaluations'] : [])].some((key) => submitted[key] !== chosen.liveReport[key])

  return <div dir="rtl" className="space-y-5">
    <div className={box}>
      <div className="flex items-start gap-3"><span className="rounded-xl bg-violet-50 p-2 text-violet-700"><ClipboardCheck size={20} /></span><div><h2 className="text-lg font-bold text-gray-900">الحضور وتسليم الشيفت</h2><p className="mt-1 text-sm text-gray-600">الحالات المفتوحة تُقرأ مباشرة من سجلاتها. التقرير يرسل نسخة من أرقام الحصص وقت التسليم، مع خلاصة تكتبها أنت.</p></div></div>
    </div>
    {feed.isError && <p role="alert" className="text-sm text-red-700">تعذّر تحميل تسليمات الشيفت السابق.</p>}
    {!!feed.data?.length && <section className={box}><h3 className="mb-3 flex items-center gap-2 font-bold text-gray-900"><UsersRound size={18} /> آخر التسليمات للفريق</h3><div className="grid gap-2 sm:grid-cols-2">{feed.data.slice(0, 6).map((row) => <div key={row._id} className="rounded-xl bg-gray-50 p-3 text-sm"><p className="font-semibold text-gray-800">{name(row.memberId)} · {row.shiftId?.name}</p><p className="mt-1 whitespace-pre-wrap text-gray-700">{row.handoffNote}</p><p className="mt-2 text-xs font-semibold text-amber-800">المعلق الآن باسم {name(row.memberId)}</p>{row.openCases?.map((item) => <p key={item._id} className="mt-1 text-xs text-gray-700">حالة: {item.reason} · {date(item.followUpAt)}</p>)}{row.openActions?.map((item) => <p key={item._id} className="mt-1 text-xs text-gray-700">متابعة: {item.description}</p>)}{row.queueTruncated && <p className="mt-1 text-xs text-amber-800">قد توجد حالات إضافية في صفحة الحالات.</p>}<p className="mt-2 text-xs text-gray-500">{date(row.handedOffAt)}</p></div>)}</div></section>}
    <section className={box}><h3 className="mb-3 font-bold text-gray-900">الشيفتات والتقارير</h3>
      {records.isLoading && <p className="text-sm text-gray-600">جارٍ تحميل الشيفتات...</p>}
      {records.isError && <p role="alert" className="text-sm text-red-700">تعذّر تحميل الشيفتات. أعد المحاولة.</p>}
      {!records.isLoading && !records.data?.data?.length && <p className="text-sm text-gray-600">لا توجد شيفتات مسجلة لهذا الفريق.</p>}
      <div className="space-y-3">{records.data?.data?.map((shift) => <article key={shift._id} className="rounded-xl border border-gray-100 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><h4 className="font-bold text-gray-900">{shift.name}</h4><p className="text-xs text-gray-600">{date(shift.startsAt)} — {date(shift.endsAt)}</p></div><span className="rounded-lg bg-violet-50 px-2 py-1 text-xs text-violet-800">{shift.members?.length || 0} أعضاء</span></div>
        <div className="mt-3 flex flex-wrap gap-2">{shift.records?.filter((row) => manager || String(row.member?._id) === String(user?._id)).map((row) => <button key={row.member?._id} onClick={() => { setSelection({ shiftId: shift._id, memberId: row.member?._id }); setNote(''); setAnalysis('') }} className={`min-h-11 rounded-xl border px-3 py-2 text-right text-sm ${selection?.shiftId === shift._id && selection?.memberId === row.member?._id ? 'border-violet-400 bg-violet-50' : 'border-gray-200 bg-white'}`}><span className="font-semibold">{name(row.member)}</span><span className="block text-xs text-gray-600">{stateLabel[row.handoff]} · {stateLabel[row.report]}</span></button>)}</div>
      </article>)}</div>
      <div className="mt-4 flex items-center justify-between text-sm text-gray-600"><span>صفحة {page} من {Math.max(1, records.data?.totalPages || 1)}</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => { setPage(page - 1); setSelection(null) }} className="min-h-11 rounded-lg border px-3 disabled:opacity-40">السابق</button><button disabled={page >= (records.data?.totalPages || 1)} onClick={() => { setPage(page + 1); setSelection(null) }} className="min-h-11 rounded-lg border px-3 disabled:opacity-40">التالي</button></div></div>
    </section>
    {selection && <section className={box}>{detail.isLoading ? <p className="text-sm text-gray-600">جارٍ تحميل المحضر...</p> : detail.isError ? <p role="alert" className="text-sm text-red-700">تعذّر تحميل المحضر.</p> : chosen && <>
      <div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-bold text-gray-900">محضر {name(chosen.member)}</h3><p className="mt-1 text-sm text-gray-600">{chosen.shift.name} · نهاية الشيفت {date(chosen.shift.endsAt)}</p></div><div className="text-sm"><p className="font-semibold text-gray-800">{stateLabel[chosen.handoff]} · {stateLabel[chosen.report]}</p><p className="text-gray-600">آخر موعد للتقرير {date(chosen.dueAt)}</p></div></div>
      <div className="mt-4 grid gap-3 sm:grid-cols-3"><Stat label="الحضور" value={date(chosen.record?.checkedInAt)} /><Stat label="الانصراف" value={date(chosen.record?.checkedOutAt)} /><Stat label="تسليم الحالات" value={date(chosen.record?.handedOffAt)} /></div>
      {myRecord && <div className="mt-4 flex flex-wrap gap-2">{!chosen.record?.checkedInAt && <button disabled={action.isPending || now < new Date(chosen.shift.startsAt).getTime() - 1800000 || now > new Date(chosen.shift.endsAt).getTime()} onClick={() => action.mutate({ kind: 'in', shiftId: selection.shiftId })} className={button}>تسجيل بداية الشيفت</button>}{chosen.record?.checkedInAt && !chosen.record?.checkedOutAt && <button disabled={action.isPending || now < new Date(chosen.shift.startsAt).getTime()} onClick={() => action.mutate({ kind: 'out', shiftId: selection.shiftId })} className={button}>تسجيل الانصراف</button>}</div>}
      <div className="mt-5 grid gap-3 sm:grid-cols-2"><Stat label="حالات مفتوحة باسمي الآن" value={chosen.queue.caseCount} /><Stat label="متابعات مفتوحة باسمي الآن" value={chosen.queue.actionCount} /></div>
      <div className="mt-3 space-y-2">{chosen.queue.cases.map((row) => <div key={row._id} className="rounded-xl bg-amber-50 p-3 text-sm text-gray-800">{row.reason} <span className="text-xs text-gray-600">· متابعة {date(row.followUpAt)}</span></div>)}{chosen.queue.actions.map((row) => <div key={row._id} className="rounded-xl bg-amber-50 p-3 text-sm text-gray-800">{row.description}</div>)}{chosen.queue.truncated && <p className="text-sm text-amber-800">توجد حالات أخرى. راجع صفحة الحالات والحلقات للاطلاع عليها كلها.</p>}</div>
      {chosen.record?.handoffNote && <p className="mt-4 whitespace-pre-wrap rounded-xl bg-violet-50 p-3 text-sm text-gray-800">{chosen.record.handoffNote}</p>}
      {myRecord && !chosen.record?.handedOffAt && <form onSubmit={(event) => { event.preventDefault(); action.mutate({ kind: 'handoff', shiftId: selection.shiftId, value: note }) }} className="mt-4 space-y-2"><label className="block text-sm font-bold text-gray-800" htmlFor="handoff-note">ما يحتاجه الشيفت التالي</label><textarea id="handoff-note" required maxLength={2000} value={note} onChange={(event) => setNote(event.target.value)} className={input} rows={3} placeholder="اكتب القرار أو الخطوة التالية فقط؛ الحالات وأصحابها تظهر تلقائيًا" /><button className={button} disabled={action.isPending || now < new Date(chosen.shift.endsAt).getTime() - 1800000}>تسليم الحالات الآن</button></form>}
      <div className="mt-5 border-t border-gray-100 pt-4"><h4 className="flex items-center gap-2 font-bold text-gray-900"><FileText size={18} /> تقرير نهاية الشيفت R2</h4><p className="mt-1 text-xs text-gray-600">الأعداد من الحصص وسجل حضور الطالب والحالات. بدء المعلم عبر المنصة لا يثبت دخوله اجتماع Zoom أو Meet. حضور المشرف يُحسب فقط من تقرير متابعة أعلن فيه حضور الحصة.</p><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4"><Stat label="إجمالي الحصص" value={chosen.record?.reportSnapshot?.total ?? chosen.liveReport.total} /><Stat label="المكتملة" value={chosen.record?.reportSnapshot?.completed ?? chosen.liveReport.completed} /><Stat label="حضور الطلاب المسجل" value={chosen.record?.reportSnapshot?.studentPresent ?? chosen.liveReport.studentPresent} /><Stat label="غياب الطلاب المسجل" value={chosen.record?.reportSnapshot?.studentAbsent ?? chosen.liveReport.studentAbsent} /><Stat label="إشارات بدء المعلمين" value={chosen.record?.reportSnapshot?.teacherStarted ?? chosen.liveReport.teacherStarted} /><Stat label="بلاغات اعتذار" value={chosen.record?.reportSnapshot?.apologies ?? chosen.liveReport.apologies} /><Stat label="بلاغات غياب" value={chosen.record?.reportSnapshot?.absences ?? chosen.liveReport.absences} /><Stat label="لم تتم/غياب الحصة" value={chosen.record?.reportSnapshot?.noShow ?? chosen.liveReport.noShow} />{chosen.shift.team === 'academic' && <><Stat label="حلقات شاهدها المشرف" value={chosen.record?.reportSnapshot?.observedLessons ?? chosen.liveReport.observedLessons} /><Stat label="تقارير المشاهدة المرسلة" value={chosen.record?.reportSnapshot?.observedReportsSubmitted ?? chosen.liveReport.observedReportsSubmitted} /><Stat label="حلقات مقيمة" value={chosen.record?.reportSnapshot?.observedEvaluations ?? chosen.liveReport.observedEvaluations} /></>}</div>
      {sourceChanged && <p role="status" className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-900">تغيّرت بيانات بعض الحصص أو الحالات بعد إرسال التقرير. الأرقام أعلاه هي النسخة التي سُلّمت؛ راجع السجلات الحية قبل اعتماد أي تصحيح.</p>}
      {submitted?.handoffOpen && <p className="mt-3 text-sm text-gray-700">عند إرسال التقرير كان هناك {submitted.handoffOpen.caseCount} حالة و{submitted.handoffOpen.actionCount} متابعة مفتوحة باسم صاحب الشيفت. القائمة الحالية تظهر أعلى الصفحة.</p>}
      {!!(chosen.record?.reportSnapshot?.completedLessons || chosen.liveReport.completedLessons)?.length && <div className="mt-3"><p className="text-sm font-semibold text-gray-800">الحلقات المكتملة</p><div className="mt-1 max-h-40 space-y-1 overflow-y-auto text-sm text-gray-600">{(chosen.record?.reportSnapshot?.completedLessons || chosen.liveReport.completedLessons).map((row) => <p key={row.sessionId}>{date(row.scheduledAt)} · {name(row.teacher)} مع {name(row.student)}</p>)}</div></div>}
      {!!(chosen.record?.reportSnapshot?.observedLessonRows || chosen.liveReport.observedLessonRows)?.length && <div className="mt-3"><p className="text-sm font-semibold text-gray-800">الحلقات التي شهد المشرف متابعتها</p><div className="mt-1 max-h-40 space-y-1 overflow-y-auto text-sm text-gray-600">{(chosen.record?.reportSnapshot?.observedLessonRows || chosen.liveReport.observedLessonRows).map((row) => <p key={row.sessionId}>{date(row.scheduledAt)} · {name(row.teacher)} مع {name(row.student)} · {row.reportSubmitted ? 'تقرير مرسل' : 'تقرير لم يُرسل بعد'}</p>)}</div>{(chosen.record?.reportSnapshot?.observedLessonsTruncated ?? chosen.liveReport.observedLessonsTruncated) && <p className="text-xs text-amber-700">توجد حلقات أخرى؛ القائمة تعرض أول 50 حصة فقط.</p>}</div>}
      {[['حالات الاعتذار', 'apologyCases'], ['حالات الغياب', 'absenceCases']].map(([label, key]) => { const cases = (submitted || chosen.liveReport)[key] || []; return cases.length ? <div key={key} className="mt-3"><p className="text-sm font-semibold text-gray-800">{label}</p><div className="mt-1 space-y-1">{cases.map((row) => <div key={row._id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg bg-gray-50 px-3 py-2 text-sm text-gray-700"><span>{row.reason}</span><button type="button" onClick={() => onOpenException?.(row.sessionId)} className="min-h-11 font-bold text-violet-700">فتح الحالة</button></div>)}</div></div> : null })}
      {chosen.record?.analysis && <p className="mt-4 whitespace-pre-wrap rounded-xl bg-gray-50 p-3 text-sm text-gray-800">{chosen.record.analysis}</p>}
      {myRecord && !chosen.record?.reportSubmittedAt && <form onSubmit={(event) => { event.preventDefault(); action.mutate({ kind: 'report', shiftId: selection.shiftId, value: analysis }) }} className="mt-4 space-y-2"><label className="block text-sm font-bold text-gray-800" htmlFor="report-analysis">خلاصة المشرف وتوصياته</label><textarea id="report-analysis" required maxLength={4000} value={analysis} onChange={(event) => setAnalysis(event.target.value)} className={input} rows={4} /><div className="flex flex-wrap gap-2"><button type="button" onClick={() => action.mutate({ kind: 'draft', shiftId: selection.shiftId, value: analysis })} className="min-h-11 rounded-xl border border-violet-200 px-4 text-sm font-bold text-violet-700 disabled:opacity-50" disabled={action.isPending || !analysis.trim() || now < new Date(chosen.shift.startsAt).getTime()}>حفظ مسودة</button><button className={button} disabled={action.isPending || now < new Date(chosen.shift.endsAt).getTime()}>إرسال التقرير</button></div></form>}</div>
      {chosen.finance && <div className="mt-5 border-t border-gray-100 pt-4"><h4 className="flex items-center gap-2 font-bold text-gray-900"><Clock3 size={18} /> ملخص الحسابات المصرح بها</h4><p className="mt-1 text-xs text-gray-600">من دفتر الحركات الفعلي خلال مدة الشيفت؛ قد تختلف الأرقام إذا صُححت الحركات لاحقًا.</p><div className="mt-2 flex flex-wrap gap-2 text-sm"><span className="rounded-lg bg-gray-50 px-3 py-2">طلبات تسوية معلقة: {chosen.finance.pendingAdjustments}</span>{chosen.finance.payroll.map((row) => <span key={row._id} className="rounded-lg bg-gray-50 px-3 py-2">مستحقات {row._id}: {row.amount}</span>)}{chosen.finance.lessons.map((row) => <span key={row._id} className="rounded-lg bg-gray-50 px-3 py-2">{row._id}: {row.amount} حصة</span>)}</div></div>}
    </>}</section>}
  </div>
}

function Stat({ label, value }) { return <div className="rounded-xl bg-gray-50 p-3"><p className="text-xs text-gray-600">{label}</p><p className="mt-1 break-words text-sm font-bold text-gray-900">{value ?? '—'}</p></div> }
