import { useEffect, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import toast from 'react-hot-toast'
import { Search, BarChart3, FileText, CheckCircle2, AlertCircle } from 'lucide-react'
import { supervisionService } from '../../services/supervision.service.js'
import { academyDateKey } from '../../utils/date.js'
import AcademicRecognitionPanel from './AcademicRecognitionPanel.jsx'

const input = 'min-h-11 w-full rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm text-gray-900 outline-none focus:border-violet-500'
const box = 'rounded-2xl border border-gray-100 bg-white p-5 shadow-sm'
const button = 'min-h-11 rounded-xl bg-violet-600 px-4 text-sm font-bold text-white disabled:opacity-50'
const name = (person) => person ? `${person.firstNameAr || ''} ${person.lastNameAr || ''}`.trim() : '—'
const date = (value) => value ? new Date(value).toLocaleString('ar-EG-u-nu-latn', { dateStyle: 'medium', timeStyle: 'short' }) : '—'
const cairoDay = (value) => new Date(value).toLocaleDateString('en-CA', { timeZone: 'Africa/Cairo' })
const today = () => academyDateKey(new Date())
const startOf = (value, type) => { const d = new Date(`${value}T12:00:00Z`); if (type === 'R3') d.setUTCDate(d.getUTCDate() - (d.getUTCDay() + 6) % 7); if (type === 'R4') d.setUTCDate(1); return d.toISOString().slice(0, 10) }
const analysisFields = [['achievements', 'إنجازات الإشراف'], ['challenges', 'المشكلات والتحديات'], ['actions', 'الإجراءات المتخذة'],
  ['recommendations', 'التوصيات والحلول'], ['generalNotes', 'ملاحظات عامة'], ['strength', 'أبرز نقطة قوة'], ['improvement', 'أهم نقطة تطوير'], ['nextGoal', 'هدف الفترة القادمة']]
const nominationFields = [['distinguishedTeachers', 'المعلمون المتميزون'], ['teachersNeedingSupport', 'معلمون يحتاجون متابعة'],
  ['distinguishedStudents', 'طلاب متميزون'], ['studentsNeedingSupport', 'طلاب يحتاجون تدخلًا']]
const ratings = [['excellent', 'ممتاز'], ['very_good', 'جيد جدًا'], ['good', 'جيد'], ['needs_improvement', 'يحتاج تحسينًا']]
const observationCategories = { lesson_quality: 'جودة الحلقة', teacher_commitment: 'التزام المعلم', student_progress: 'تقدم الطالب', curriculum: 'المنهج', attendance: 'الحضور', technical: 'مشكلة تقنية', other: 'أخرى' }
const stateLabel = { draft: 'مسودة', submitted: 'بانتظار المدير', changes_requested: 'تحتاج استكمالًا', approved: 'معتمد' }
const emptyAnalysis = { achievements: '', challenges: '', actions: '', recommendations: '', generalNotes: '', strength: '', improvement: '', nextGoal: '', rating: '',
  distinguishedTeachers: [], teachersNeedingSupport: [], distinguishedStudents: [], studentsNeedingSupport: [] }

function MetricCards({ data, academic = true, onSelect, selected }) {
  const counts = data?.counts || {}
  const cards = [['الحلقات المميزة', counts.total, ''], ['حضور الطالب المثبت', counts.attended, 'attended'], ['الاعتذارات', counts.apology, 'apology'], ['الغياب', counts.absent, 'absent'],
    ...(academic ? [['متابعة المشرف', counts.observed, 'observed'], ['تقييم R1', counts.rated, 'rated'], ['تقرير R1 مرسل', counts.submitted, 'submitted']] : []), ['غير محسومة', counts.unresolved + counts.unknown, 'open']]
  return <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, filter]) => <button type="button" disabled={!onSelect} onClick={() => onSelect?.(filter)} key={label} className={`rounded-2xl border bg-white p-4 text-right shadow-sm disabled:cursor-default ${selected === filter && onSelect ? 'border-violet-500 ring-2 ring-violet-100' : 'border-gray-100'}`}><p className="text-sm text-gray-600">{label}</p><p className="mt-2 text-3xl font-extrabold text-[#281343]">{value ?? '—'}</p></button>)}</div>
    <p className="rounded-xl bg-violet-50 p-4 text-sm leading-7 text-violet-950">{data?.percentages ? `الحضور ${data.percentages.attended}% · الغياب ${data.percentages.absent}% · الاعتذارات ${data.percentages.apology}%` : 'لا توجد حلقات تدخل في مقام النسب خلال الفترة.'} المقام {data?.denominator ?? 0} حلقة، ويستبعد الملغاة ({counts.cancelled || 0}). المتابعة والتقييم وإرسال التقرير عدادات مختلفة للحصص المميزة. {data?.source?.note}</p>
    {academic && data?.achievements && <div className="grid gap-3 sm:grid-cols-3">{[['memorization', 'سجلات حفظ'], ['revision', 'سجلات مراجعة'], ['evaluation', 'تقييمات طلاب']].map(([key, label]) => <div key={key} className="rounded-xl border border-emerald-100 bg-emerald-50 p-4"><p className="text-sm text-emerald-900">{label}</p><strong className="mt-1 block text-2xl text-emerald-950">{data.achievements[key]?.records ?? 0}</strong><small className="text-emerald-900">لـ {data.achievements[key]?.students ?? 0} طلاب</small></div>)}</div>}
    {academic && <div className="rounded-xl border border-gray-100 bg-white p-4"><h4 className="font-bold text-gray-900">الملاحظات الأكاديمية المصنفة</h4><p className="mt-1 text-xs text-gray-600">عدد تقارير المتابعة المرسلة بحسب التصنيف المختار. التقارير القديمة وغير المصنفة لا تدخل في هذه الأعداد.</p><div className="mt-3 flex flex-wrap gap-2">{data?.observationCategories?.length ? data.observationCategories.map((item) => <span key={item._id} className="rounded-full bg-violet-50 px-3 py-1 text-sm text-violet-900">{observationCategories[item._id] || item._id}: {item.reports}</span>) : <span className="text-sm text-gray-500">لا توجد ملاحظات مصنفة في هذه الفترة.</span>}</div></div>}
    </>
}

export default function SupervisionPeriodicSection({ user, team = 'academic', mode = 'metrics', onOpenLearning, onOpenReport }) {
  const leader = Boolean(user?.isPrimaryAdmin || user?.role === 'admin' || user?.supervisionPosition === 'manager')
  const academic = team === 'academic'
  const qc = useQueryClient()
  const [kind, setKind] = useState('day')
  const [day, setDay] = useState(today)
  const [shiftId, setShiftId] = useState('')
  const [category, setCategory] = useState('')
  const [supervisorId, setSupervisorId] = useState('')
  const [reportType, setReportType] = useState('R3')
  const [reportId, setReportId] = useState('')
  const [analysis, setAnalysis] = useState(emptyAnalysis)
  const [reviewNote, setReviewNote] = useState('')
  const [search, setSearch] = useState('')
  const [candidateQuery, setCandidateQuery] = useState('')
  const [candidateField, setCandidateField] = useState('')
  const [reason, setReason] = useState('')
  const [evidence, setEvidence] = useState('')
  const [page, setPage] = useState(1)
  const [evidenceFilter, setEvidenceFilter] = useState('')
  const [evidencePage, setEvidencePage] = useState(1)
  const [teacherPage, setTeacherPage] = useState(1)
  useEffect(() => { setEvidencePage(1); setTeacherPage(1) }, [team, kind, day, shiftId, category, supervisorId])
  const reportStart = startOf(day, reportType)
  const metricsKind = mode === 'reports' ? reportType === 'R3' ? 'week' : 'month' : kind
  const start = startOf(day, metricsKind === 'week' ? 'R3' : metricsKind === 'month' ? 'R4' : '')
  const metricParams = { team, type: mode === 'reports' ? reportType : undefined, start,
    supervisorId: leader ? supervisorId || undefined : undefined, shiftId: mode === 'metrics' ? shiftId || undefined : undefined,
    category: mode === 'metrics' ? category || undefined : undefined,
    evidence: mode === 'metrics' ? evidenceFilter || undefined : undefined, page: mode === 'metrics' ? evidencePage : undefined,
    teacherPage: mode === 'metrics' ? teacherPage : undefined }
  const summary = useQuery({ queryKey: ['supervision', 'periodic-metrics', metricParams], queryFn: () => supervisionService.periodicMetrics(metricParams), enabled: mode !== 'search' })
  const shifts = useQuery({ queryKey: ['supervision', 'periodic-shifts', team, start], queryFn: () => supervisionService.shifts({ team, history: true, limit: 50 }), enabled: mode === 'metrics' })
  const people = useQuery({ queryKey: ['supervision', 'periodic-people', team], queryFn: () => supervisionService.people({ team, position: 'supervisor', limit: 50 }), enabled: Boolean(leader && mode !== 'search') })
  const subjects = useQuery({ queryKey: ['supervision', 'subjects'], queryFn: supervisionService.subjects, enabled: mode === 'metrics' })
  const reports = useQuery({ queryKey: ['supervision', 'periodic-reports', reportType, page], queryFn: () => supervisionService.periodicReports({ type: reportType, page, limit: 20 }), enabled: mode === 'reports' })
  const detail = useQuery({ queryKey: ['supervision', 'periodic-report', reportId], queryFn: () => supervisionService.periodicReport(reportId), enabled: mode === 'reports' && !!reportId })
  const results = useQuery({ queryKey: ['supervision', 'academic-search', search], queryFn: () => supervisionService.academicSearch(search), enabled: mode === 'search' && search.trim().length >= 2 })
  const candidates = useQuery({ queryKey: ['supervision', 'academic-candidates', candidateQuery], queryFn: () => supervisionService.academicSearch(candidateQuery), enabled: mode === 'reports' && candidateQuery.trim().length >= 2 })
  useEffect(() => { if (detail.data?.analysis) setAnalysis({ ...emptyAnalysis, ...detail.data.analysis }) }, [detail.data])
  const refresh = () => { qc.invalidateQueries({ queryKey: ['supervision', 'periodic'] }) }
  const error = (err) => toast.error(err.response?.data?.message || 'تعذر حفظ البيانات')
  const save = useMutation({ mutationFn: () => supervisionService.savePeriodicReport({ type: reportType, start: reportStart, analysis }), onSuccess: ({ data }) => { setReportId(data.data._id); toast.success('حُفظت المسودة'); refresh() }, onError: error })
  const submit = useMutation({ mutationFn: () => supervisionService.submitPeriodicReport(reportId), onSuccess: () => { toast.success('أُرسل التقرير للمدير'); refresh() }, onError: error })
  const review = useMutation({ mutationFn: (decision) => supervisionService.reviewPeriodicReport(reportId, { decision, note: reviewNote }), onSuccess: () => { toast.success('سُجل قرار المراجعة'); setReviewNote(''); refresh() }, onError: error })
  const correct = useMutation({ mutationFn: () => supervisionService.correctPeriodicReport(reportId, { reason: reviewNote, analysis }), onSuccess: () => { toast.success('سُجل التصحيح كنسخة جديدة'); setReviewNote(''); refresh() }, onError: error })
  const selected = detail.data
  const editable = !leader && (!reportId || !!selected && ['draft', 'changes_requested'].includes(selected.status))

  if (mode === 'search') return <section className={box}><div className="flex items-center gap-2"><Search size={20} className="text-violet-700" /><h2 className="text-xl font-bold">بحث أكاديمي موحد</h2></div><p className="mt-1 text-sm text-gray-600">النتائج محدودة بصلاحيتك؛ ابحث باسم أو عنوان حصة أو كلمة من ملاحظات R1.</p><input className={`${input} mt-4`} value={search} onChange={(event) => setSearch(event.target.value)} placeholder="اكتب حرفين على الأقل" aria-label="بحث أكاديمي" />
    {results.isLoading && <p className="mt-4 text-sm">جارٍ البحث...</p>}{results.isError && <p role="alert" className="mt-4 text-sm text-red-700">تعذر البحث.</p>}
    {results.data && <div className="mt-4 grid gap-3 md:grid-cols-2">{[['students', 'الطلاب'], ['teachers', 'المعلمون'], ['supervisors', 'المشرفون'], ['sessions', 'الحلقات'], ['reports', 'تقارير R1']].map(([key, label]) => <div key={key} className="rounded-xl border p-4"><h3 className="font-bold">{label}</h3>{results.data[key]?.length ? results.data[key].map((row) => <button key={row._id} onClick={() => key === 'students' ? onOpenLearning?.({ studentId: row._id }) : key === 'teachers' ? onOpenLearning?.({ teacherId: row._id }) : key === 'sessions' ? onOpenReport?.({ sessionId: row._id, day: row.scheduledAt }) : key === 'reports' ? onOpenReport?.({ sessionId: row.sessionId, reportId: row._id, day: row.scheduledAt }) : key === 'supervisors' ? onOpenLearning?.({ supervisorId: row._id }) : null} className="mt-2 block min-h-11 w-full rounded-lg bg-gray-50 px-3 text-right text-sm hover:bg-violet-50">{row.titleAr || (key === 'reports' ? 'تقرير متابعة' : name(row))} {row.scheduledAt ? `· ${date(row.scheduledAt)}` : ''}</button>) : <p className="mt-2 text-sm text-gray-500">لا توجد نتائج</p>}</div>)}</div>}
  </section>

  return <div className="space-y-4"><section className={box}><div className="flex items-start gap-3"><span className="rounded-xl bg-violet-50 p-2 text-violet-700">{mode === 'reports' ? <FileText size={20} /> : <BarChart3 size={20} />}</span><div><h2 className="text-xl font-bold text-gray-900">{mode === 'reports' ? 'التقارير الأكاديمية R3 وR4' : 'الإحصاءات من السجلات'}</h2><p className="mt-1 text-sm leading-6 text-gray-600">{mode === 'reports' ? 'الأرقام تُحسب آليًا، والتحليل والترشيحات قرار بشري يراجعه مدير الأكاديمي.' : 'كل حصة تُحسب مرة واحدة، مع فصل حضور الطالب عن متابعة المشرف.'}</p></div></div>
    <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{mode === 'reports' ? <label className="text-sm font-semibold">نوع التقرير<select className={input} value={reportType} onChange={(event) => { setReportType(event.target.value); setReportId(''); setAnalysis(emptyAnalysis); setPage(1) }}><option value="R3">أسبوعي R3</option><option value="R4">شهري R4</option></select></label> : <label className="text-sm font-semibold">الفترة<select className={input} value={kind} onChange={(event) => setKind(event.target.value)}><option value="day">يومي</option><option value="week">أسبوعي</option><option value="month">شهري</option></select></label>}
      <label className="text-sm font-semibold">{mode === 'reports' ? 'تاريخ داخل الفترة' : 'التاريخ'}<input className={input} type="date" value={day} onChange={(event) => { setDay(event.target.value); if (mode === 'reports') { setReportId(''); setAnalysis(emptyAnalysis) } }} /></label>
      {leader && <label className="text-sm font-semibold">المشرف<select className={input} value={supervisorId} onChange={(event) => setSupervisorId(event.target.value)}><option value="">كل الفريق</option>{(people.data?.data || []).map((row) => <option value={row._id} key={row._id}>{name(row)}</option>)}</select></label>}
      {mode === 'metrics' && <><label className="text-sm font-semibold">الشيفت<select className={input} value={shiftId} onChange={(event) => setShiftId(event.target.value)}><option value="">كل الشيفتات</option>{(shifts.data?.data || []).map((row) => <option key={row._id} value={row._id}>{row.name} · {date(row.startsAt)}</option>)}</select></label><label className="text-sm font-semibold">فئة المعلم<select className={input} value={category} onChange={(event) => setCategory(event.target.value)}><option value="">كل الفئات</option>{(subjects.data?.data || []).map((row) => <option key={row.key} value={row.key}>{row.nameAr}</option>)}</select></label></>}</div><p className="mt-2 text-xs text-gray-600">الفترة تبدأ {start} بتوقيت الأكاديمية. {mode === 'reports' && 'التقرير الفردي للمشرف؛ بيانات المدير المجمعة تظهر في المؤشرات.'}</p></section>
    {summary.isLoading && <p className={box}>جارٍ حساب الأرقام من السجلات...</p>}{summary.isError && <p role="alert" className={box}>تعذر حساب الإحصاءات. <button className="text-violet-700 underline" onClick={() => summary.refetch()}>إعادة المحاولة</button></p>}
    {summary.data && <MetricCards data={summary.data} academic={academic} selected={evidenceFilter} onSelect={mode === 'metrics' ? (value) => { setEvidenceFilter(value); setEvidencePage(1) } : undefined} />}
    {mode === 'metrics' && summary.data && <><section className={box}><h3 className="font-bold">مصادر المؤشر {evidenceFilter && `· ${evidenceFilter}`}</h3><p className="mt-1 text-xs text-gray-600">اضغط بطاقة مؤشر لعرض الحصص الداخلة فيه. {summary.data.evidenceTotal} سجل مطابق.</p><div className="mt-3 space-y-2">{summary.data.samples?.map((row) => <button key={row._id} onClick={() => onOpenReport?.({ sessionId: row._id, day: row.scheduledAt })} className="flex min-h-11 w-full flex-wrap justify-between gap-2 rounded-xl bg-gray-50 px-3 py-2 text-right text-sm hover:bg-violet-50"><span>حصة {date(row.scheduledAt)} · {row.bucket}</span>{academic && <span>{row.observed ? 'متابعة مثبتة' : 'بلا متابعة مثبتة'} · {row.rated ? 'مقيمة' : 'بلا تقييم'}</span>}</button>)}</div>{!summary.data.samples?.length && <p className="mt-3 text-sm text-gray-500">لا توجد حلقات في الفترة.</p>}<div className="mt-3 flex gap-2 text-sm"><button className="min-h-11 rounded-xl border px-4 disabled:opacity-40" disabled={evidencePage === 1} onClick={() => setEvidencePage(evidencePage - 1)}>السابق</button><button className="min-h-11 rounded-xl border px-4 disabled:opacity-40" disabled={evidencePage * 20 >= summary.data.evidenceTotal} onClick={() => setEvidencePage(evidencePage + 1)}>التالي</button></div></section><section className={box}><h3 className="font-bold">ملخص المعلمين</h3><p className="mt-1 text-xs text-gray-600">هذه أعداد تشغيل، وليست ترتيب جودة أو نقاط تقييم. {summary.data.teacherTotal || 0} معلمًا ضمن الفترة.</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{summary.data.teachers?.map((row) => <button key={row._id} onClick={() => academic ? onOpenLearning?.({ teacherId: row._id }) : null} className="min-h-11 rounded-xl border px-3 py-2 text-right text-sm hover:bg-violet-50">{row.name} · {row.total} حلقة{academic && ` · ${row.observed} متابعة · ${row.rated} تقييم`}</button>)}</div><div className="mt-3 flex gap-2 text-sm"><button className="min-h-11 rounded-xl border px-4 disabled:opacity-40" disabled={teacherPage === 1} onClick={() => setTeacherPage(teacherPage - 1)}>السابق</button><button className="min-h-11 rounded-xl border px-4 disabled:opacity-40" disabled={teacherPage * 20 >= summary.data.teacherTotal} onClick={() => setTeacherPage(teacherPage + 1)}>التالي</button></div></section></>}
    {mode === 'reports' && academic && <><section className={box}><div className="flex flex-wrap justify-between gap-2"><h3 className="font-bold">التقارير المحفوظة</h3>{!leader && <button className="min-h-11 text-sm font-bold text-violet-700" onClick={() => { setReportId(''); setAnalysis(emptyAnalysis) }}>مسودة جديدة لهذه الفترة</button>}</div>{reports.isError && <p role="alert" className="text-red-700">تعذر تحميل التقارير.</p>}{reports.isLoading && <p>جارٍ التحميل...</p>}{(reports.data?.data || []).map((row) => <button key={row._id} onClick={() => { setReportId(row._id); setDay(cairoDay(row.periodStart)) }} className={`mt-2 flex min-h-11 w-full flex-wrap justify-between gap-2 rounded-xl px-3 py-2 text-right text-sm ${reportId === row._id ? 'bg-violet-100' : 'bg-gray-50'}`}><span>{row.type} · {name(row.supervisorId)} · {date(row.periodStart)}</span><strong>{stateLabel[row.status]}</strong></button>)}<div className="mt-3 flex gap-2 text-sm"><button disabled={page === 1} className="min-h-11 rounded-xl border px-4 disabled:opacity-40" onClick={() => setPage(page - 1)}>السابق</button><button disabled={!reports.data?.hasMore} className="min-h-11 rounded-xl border px-4 disabled:opacity-40" onClick={() => setPage(page + 1)}>التالي</button></div></section>
      {(reportId || !leader) && <section className={box}><div className="flex flex-wrap justify-between gap-2"><h3 className="font-bold">{selected ? `${selected.type} · ${stateLabel[selected.status]} · النسخة ${selected.version}` : 'مسودة جديدة'}</h3>{selected?.sourcesChanged && <span className="flex items-center gap-1 text-sm font-bold text-amber-800"><AlertCircle size={16} /> تغيّرت بيانات المصدر بعد آخر حساب</span>}</div>{detail.isLoading && <p>جارٍ فتح التقرير...</p>}{detail.isError && <p role="alert" className="text-red-700">تعذر فتح التقرير.</p>}
        {selected?.metricsSnapshot && <div className="mt-4"><MetricCards data={selected.metricsSnapshot} /><p className="mt-2 text-xs text-gray-500">لقطة معتمدة وقت الإرسال {date(selected.submittedAt)} · المصدر: الحصص والحضور والاستثناءات وتقارير R1. تغيّر المصدر لا يعدل النسخة القديمة.</p></div>}
        {selected?.shiftSnapshot?.length > 0 && <details className="mt-3 rounded-xl bg-gray-50 p-3 text-sm"><summary className="cursor-pointer font-bold">الشيفتات الفعلية في الفترة</summary>{selected.shiftSnapshot.map((row) => <p key={row._id} className="mt-2">{row.name} · {date(row.startsAt)} — {date(row.endsAt)}</p>)}</details>}
        {selected && !editable && (!leader || selected.status !== 'approved') && <div className="mt-4 space-y-3"><p className="text-sm font-bold">التقييم الوصفي: {ratings.find(([value]) => value === selected.analysis?.rating)?.[1] || 'لم يحدد'}</p><div className="grid gap-2 sm:grid-cols-2">{analysisFields.filter(([key]) => selected.analysis?.[key]).map(([key, label]) => <p key={key} className="whitespace-pre-wrap rounded-xl bg-gray-50 p-3 text-sm"><strong>{label}:</strong> {selected.analysis[key]}</p>)}</div>{nominationFields.map(([key, label]) => selected.analysis?.[key]?.length ? <div key={key} className="rounded-xl border p-3 text-sm"><strong>{label}</strong>{selected.analysis[key].map((item) => <button type="button" key={String(item.personId)} onClick={() => onOpenLearning?.(key.includes('Students') ? { studentId: String(item.personId) } : { teacherId: String(item.personId) })} className="mt-2 block min-h-11 w-full rounded-lg bg-gray-50 p-2 text-right hover:bg-violet-50">{name(selected.nomineePeople?.[String(item.personId)])} · {item.reason}{item.evidence && ` · الدليل: ${item.evidence}`}</button>)}</div> : null)}</div>}
        {(editable || leader && selected?.status === 'approved') && <div className="mt-4 space-y-3"><div className="grid gap-3 sm:grid-cols-2">{analysisFields.filter(([key]) => reportType === 'R4' || !['nextGoal', 'strength', 'improvement'].includes(key)).map(([key, label]) => <label key={key} className="text-sm font-semibold">{label}<textarea className={input} rows={3} maxLength={4000} value={analysis[key] || ''} onChange={(event) => setAnalysis({ ...analysis, [key]: event.target.value })} /></label>)}</div><label className="block text-sm font-semibold">التقييم الوصفي<select className={input} value={analysis.rating || ''} onChange={(event) => setAnalysis({ ...analysis, rating: event.target.value })}><option value="">اختر</option>{ratings.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>
          {nominationFields.map(([key, label]) => <div key={key} className="rounded-xl border p-3"><h4 className="font-bold">{label} ({analysis[key]?.length || 0})</h4>{(analysis[key] || []).map((row) => <div key={row.personId} className="mt-2 flex flex-wrap justify-between gap-2 rounded-lg bg-gray-50 p-2 text-sm"><span>{row.personId} · {row.reason} {row.evidence && `· الدليل: ${row.evidence}`}</span><button className="min-h-11 text-red-700" onClick={() => setAnalysis({ ...analysis, [key]: analysis[key].filter((item) => item.personId !== row.personId) })}>حذف</button></div>)}<button className="mt-2 min-h-11 text-sm font-semibold text-violet-700" onClick={() => setCandidateField(candidateField === key ? '' : key)}>إضافة ترشيح موثق</button>{candidateField === key && <div className="mt-2 grid gap-2 sm:grid-cols-2"><input className={input} value={candidateQuery} onChange={(event) => setCandidateQuery(event.target.value)} placeholder="ابحث عن طالب أو معلم" />{candidates.isError && <p role="alert" className="text-sm text-red-700">تعذر البحث عن مرشحين</p>}<div className="flex flex-wrap gap-2">{(key.includes('Students') ? candidates.data?.students : candidates.data?.teachers)?.map((person) => <button key={person._id} className="min-h-11 rounded-xl border px-3 text-sm" onClick={() => setCandidateQuery(`${name(person)}|${person._id}`)}>{name(person)}</button>)}</div><input className={input} value={reason} onChange={(event) => setReason(event.target.value)} placeholder="سبب الترشيح" maxLength={1000} /><input className={input} value={evidence} onChange={(event) => setEvidence(event.target.value)} placeholder="الدليل أو مرجع السجل" maxLength={1000} /><button className={button} disabled={!candidateQuery.includes('|') || !reason.trim()} onClick={() => { const personId = candidateQuery.split('|').at(-1); if ((analysis[key] || []).some((row) => row.personId === personId)) return; setAnalysis({ ...analysis, [key]: [...(analysis[key] || []), { personId, reason, evidence }] }); setCandidateQuery(''); setReason(''); setEvidence(''); setCandidateField('') }}>إضافة</button></div>}</div>)}</div>}
        {!leader && editable && <div className="mt-4 flex flex-wrap gap-2"><button className={button} disabled={save.isPending} onClick={() => save.mutate()}>حفظ المسودة</button>{selected && <button className="min-h-11 rounded-xl border border-violet-200 px-4 text-sm font-bold text-violet-700" disabled={submit.isPending} onClick={() => submit.mutate()}>إرسال للمراجعة</button>}</div>}
        {leader && selected?.status === 'submitted' && <div className="mt-4 space-y-2"><textarea className={input} value={reviewNote} onChange={(event) => setReviewNote(event.target.value)} placeholder="ملاحظة المدير، مطلوبة عند طلب الاستكمال" maxLength={1000} /><div className="flex gap-2"><button className={button} disabled={review.isPending} onClick={() => review.mutate('approved')}><CheckCircle2 size={16} className="inline" /> اعتماد</button><button className="min-h-11 rounded-xl border px-4 text-sm" disabled={review.isPending || !reviewNote.trim()} onClick={() => review.mutate('changes_requested')}>طلب استكمال</button></div></div>}
        {leader && selected?.status === 'approved' && <div className="mt-4 space-y-2"><p className="text-sm text-amber-900">التصحيح ينشئ نسخة معتمدة جديدة ويحفظ النسخة السابقة في السجل.</p><input className={input} value={reviewNote} onChange={(event) => setReviewNote(event.target.value)} placeholder="سبب التصحيح" maxLength={1000} /><button className={button} disabled={correct.isPending || !reviewNote.trim()} onClick={() => correct.mutate()}>تصحيح موثق</button></div>}
        {selected?.reviewNote && <p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-900">ملاحظة المدير: {selected.reviewNote}</p>}
        {selected?.revisions?.length > 0 && <details className="mt-4 rounded-xl bg-gray-50 p-3 text-sm"><summary className="cursor-pointer font-bold">سجل النسخ والقرارات ({selected.revisions.length})</summary>{selected.revisions.map((item, index) => <div key={`${item.at}-${index}`} className="mt-2 border-t pt-2">{date(item.at)} · {item.action} {item.note ? `· ${item.note}` : ''}{item.previous && <p>نسخة سابقة رقم {item.previous.version} محفوظة بقيمها وأرقامها.</p>}</div>)}</details>}
      </section>}{leader && reportType === 'R4' && <AcademicRecognitionPanel start={reportStart} />}</>}
  </div>
}

