import { useEffect, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import toast from 'react-hot-toast'
import api from '../../utils/api.js'
import { supervisionService } from '../../services/supervision.service.js'
import AcademicDevelopmentPanel from './AcademicDevelopmentPanel.jsx'

const input = 'min-h-11 w-full rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm outline-none focus:border-violet-500'
const format = (value) => value ? new Date(value).toLocaleDateString('ar-EG-u-nu-latn') : '—'
const name = (row) => row ? `${row.firstNameAr || ''} ${row.lastNameAr || ''}`.trim() : '—'
const rating = { excellent: 'ممتاز', very_good: 'جيد جدًا', good: 'جيد', needs_improvement: 'يحتاج تحسينًا' }
const initial = { studentId: '', subjectKey: '', courseId: '', level: '', goal: '', nextStep: '', individualNeeds: '', materialLinks: [], milestones: [] }

export default function SupervisionAcademicLearningSection({ user, initialTarget }) {
  const leader = Boolean(user?.isPrimaryAdmin || user?.role === 'admin' || user?.supervisionPosition === 'manager')
  const qc = useQueryClient()
  const [studentSearch, setStudentSearch] = useState('')
  const [studentId, setStudentId] = useState('')
  const [form, setForm] = useState(initial)
  const [milestoneTitle, setMilestoneTitle] = useState('')
  const [material, setMaterial] = useState({ title: '', url: '', visibility: 'teacher_only' })
  const [teacherSearch, setTeacherSearch] = useState('')
  const [teacherId, setTeacherId] = useState('')
  const [supervisorId, setSupervisorId] = useState('')
  useEffect(() => { if (initialTarget?.studentId) setStudentId(initialTarget.studentId); if (initialTarget?.teacherId) setTeacherId(initialTarget.teacherId); if (initialTarget?.supervisorId) setSupervisorId(initialTarget.supervisorId) }, [initialTarget])
  const [testDrafts, setTestDrafts] = useState({})
  const [milestoneStatus, setMilestoneStatus] = useState({})
  const students = useQuery({ queryKey: ['academic-students', studentSearch], queryFn: () => supervisionService.academicStudents(studentSearch), enabled: studentSearch.trim().length >= 2 })
  const subjects = useQuery({ queryKey: ['supervision', 'subjects'], queryFn: supervisionService.subjects })
  const courses = useQuery({ queryKey: ['academic-courses', form.subjectKey], queryFn: () => api.get('/courses', { params: { category: form.subjectKey, limit: 50 } }).then((r) => r.data.data), enabled: !!form.subjectKey })
  const plans = useQuery({ queryKey: ['academic-plans', studentId], queryFn: () => supervisionService.academicPlans({ studentId, limit: 30 }), enabled: !!studentId })
  const overview = useQuery({ queryKey: ['academic-student-overview', studentId], queryFn: () => supervisionService.studentAcademicOverview(studentId), enabled: !!studentId })
  const teachers = useQuery({ queryKey: ['academic-teachers', teacherSearch], queryFn: () => supervisionService.academicDirectiveRecipientsSearch(teacherSearch), enabled: Boolean(leader && teacherSearch.trim().length >= 2) })
  const assignments = useQuery({ queryKey: ['academic-my-assignments'], queryFn: () => supervisionService.assignments({ team: 'academic', limit: 50 }), enabled: !leader })
  const teacher = useQuery({ queryKey: ['academic-teacher-overview', teacherId], queryFn: () => supervisionService.teacherAcademicOverview(teacherId), enabled: !!teacherId })
  const supervisors = useQuery({ queryKey: ['academic-supervisor-people'], queryFn: () => supervisionService.people({ team: 'academic', limit: 50 }), enabled: leader })
  const supervisorProfile = useQuery({ queryKey: ['academic-supervisor-overview', supervisorId], queryFn: () => supervisionService.supervisorAcademicOverview(supervisorId), enabled: Boolean(leader && !!supervisorId) })
  const refresh = () => { qc.invalidateQueries({ queryKey: ['academic-plans'] }); qc.invalidateQueries({ queryKey: ['academic-student-overview'] }) }
  const error = (err) => toast.error(err.response?.data?.message || 'تعذر حفظ التغيير')
  const save = useMutation({ mutationFn: () => supervisionService.saveAcademicPlan({ ...form, studentId }), onSuccess: () => { toast.success('حُفظت الخطة'); refresh() }, onError: error })
  const publish = useMutation({ mutationFn: ({ id, status }) => supervisionService.publishAcademicPlan(id, status), onSuccess: () => { toast.success('تم تحديث نشر الخطة'); refresh() }, onError: error })
  const updateStep = useMutation({ mutationFn: ({ planId, stepId, data }) => supervisionService.updateAcademicMilestone(planId, stepId, data), onSuccess: () => { toast.success('تم تحديث مرحلة المنهج'); refresh() }, onError: error })

  const selectPlan = (row) => setForm({ studentId, subjectKey: row.subjectKey, courseId: row.courseId?._id || '', level: row.level || '', goal: row.goal || '',
    nextStep: row.nextStep || '', individualNeeds: row.individualNeeds || '', materialLinks: row.materialLinks || [],
    milestones: (row.milestones || []).map((step) => ({ _id: step._id, title: step.title })) })
  return <div className="space-y-5">
    <section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm">
      <h2 className="text-lg font-bold text-gray-900">ملف الطالب الأكاديمي</h2>
      <p className="mt-1 text-sm text-gray-500">الخطة ترتبط بالمنهج الموجود؛ الإنجاز مأخوذ من سجلات الحفظ والمراجعة والتقييمات، ولا يُعاد إدخاله.</p>
      <div className="mt-4 grid gap-3 sm:grid-cols-2">
        <label className="text-sm font-semibold">ابحث عن طالب<input value={studentSearch} onChange={(e) => { setStudentSearch(e.target.value); setStudentId(''); setForm(initial) }} className={`mt-1 ${input}`} placeholder="اكتب حرفين على الأقل" /></label>
        <label className="text-sm font-semibold">الطالب<select value={studentId} onChange={(e) => { setStudentId(e.target.value); setForm({ ...initial, studentId: e.target.value }) }} className={`mt-1 ${input}`}><option value="">اختر طالبًا</option>{(students.data || []).map((row) => <option key={row._id} value={row._id}>{name(row)}</option>)}</select></label>
      </div>
      {students.isError && <p role="alert" className="mt-2 text-sm text-red-700">تعذر البحث عن الطلاب</p>}
      {studentId && <div className="mt-5 space-y-4">
        {plans.isLoading && <p className="text-sm">جارٍ تحميل الخطط...</p>}
        {plans.isError && <p role="alert" className="text-sm text-red-700">تعذر تحميل خطط الطالب</p>}
        {(plans.data?.data || []).map((row) => <article key={row._id} className="rounded-xl border border-gray-100 bg-gray-50 p-4">
          <div className="flex flex-wrap justify-between gap-3">
            <div><h3 className="font-bold text-gray-900">{(subjects.data?.data || []).find((subject) => subject.key === row.subjectKey)?.nameAr || row.subjectKey} · {row.level}</h3><p className="mt-1 text-sm text-gray-600">{row.courseId?.nameAr || 'خطة فردية'} · {row.status === 'published' ? 'منشورة' : row.status === 'draft' ? 'مسودة' : 'مؤرشفة'}{row.pendingRevision && ' · تعديل ينتظر المدير'}</p></div>
            <div className="flex flex-wrap gap-2">
              <button disabled={!!row.pendingRevision} onClick={() => selectPlan(row)} className="min-h-11 rounded-lg border border-violet-200 px-3 text-sm font-bold text-violet-700 disabled:opacity-50">تعديل</button>
              {leader && (row.status !== 'published' || row.pendingRevision) && <button disabled={publish.isPending} onClick={() => publish.mutate({ id: row._id, status: 'published' })} className="min-h-11 rounded-lg bg-violet-700 px-3 text-sm font-bold text-white">{row.pendingRevision ? 'اعتماد التعديل' : 'نشر الخطة'}</button>}
              {leader && row.pendingRevision && <button disabled={publish.isPending} onClick={() => publish.mutate({ id: row._id, status: 'rejected' })} className="min-h-11 rounded-lg border border-red-200 px-3 text-sm font-bold text-red-700">رفض التعديل</button>}
              {leader && row.status === 'published' && !row.pendingRevision && <button disabled={publish.isPending} onClick={() => publish.mutate({ id: row._id, status: 'archived' })} className="min-h-11 rounded-lg border px-3 text-sm">أرشفة</button>}
            </div>
          </div>
          {row.pendingRevision && <div className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm"><strong>التعديل المقترح</strong><p className="mt-1">المقرر: {row.pendingRevision.courseName || 'خطة فردية'} · المستوى: {row.pendingRevision.level}</p><p>الهدف: {row.pendingRevision.goal}</p><p>الخطوة القادمة: {row.pendingRevision.nextStep || '—'}</p><p>الاحتياج الفردي: {row.pendingRevision.individualNeeds || '—'}</p><p>المراحل: {(row.pendingRevision.milestones || row.milestones || []).map((step) => step.title).join('، ') || '—'}</p><div className="mt-2 flex flex-wrap gap-2">{row.pendingRevision.materialLinks?.map((link) => <a key={link.url} href={link.url} target="_blank" rel="noreferrer" className="font-semibold text-violet-700 underline">{link.title} · {link.visibility === 'shared' ? 'للمعلم والطالب' : 'للمعلم'}</a>)}</div><p className="mt-2 text-xs text-gray-600">النسخة المنشورة الحالية تظل ظاهرة للطالب والمعلم حتى الاعتماد.</p></div>}
          <p className="mt-3 text-sm text-gray-700">الهدف: {row.goal}</p><p className="mt-1 text-sm text-gray-700">الخطوة القادمة: {row.nextStep || 'لم تحدد بعد'}</p>
          {!!row.individualNeeds && <p className="mt-1 text-xs text-gray-500">مراعاة الفروق الفردية: {row.individualNeeds}</p>}
          {!!row.materialLinks?.length && <div className="mt-3 flex flex-wrap gap-2">{row.materialLinks.map((link) => <a key={link.url} href={link.url} target="_blank" rel="noreferrer" className="rounded-lg bg-white px-3 py-2 text-sm text-violet-700 underline">{link.title}</a>)}</div>}
          <div className="mt-4 space-y-3">{(row.milestones || []).map((step) => <div key={step._id} className="rounded-xl bg-white p-3 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{step.title}</strong><span>{step.status === 'completed' ? 'منجز' : step.status === 'in_progress' ? 'قيد العمل' : 'مخطط'}</span></div>
            {step.externalTest?.testedAt && <p className="mt-1 text-xs text-gray-600">اختبار خارجي {format(step.externalTest.testedAt)}: {step.externalTest.result}{step.externalTest.visibleToStudent ? ' · ظاهر للطالب' : ' · داخلي'}</p>}
            <div className="mt-3 grid gap-2 sm:grid-cols-[1fr_auto]"><select aria-label="حالة مرحلة المنهج" value={milestoneStatus[step._id] || step.status} onChange={(e) => setMilestoneStatus({ ...milestoneStatus, [step._id]: e.target.value })} className={input}><option value="planned">مخطط</option><option value="in_progress">قيد العمل</option><option value="completed">منجز</option></select><button disabled={updateStep.isPending} onClick={() => updateStep.mutate({ planId: row._id, stepId: step._id, data: { status: milestoneStatus[step._id] || step.status } })} className="min-h-11 rounded-lg border px-3 font-semibold">حفظ الحالة</button></div>
            {step.status === 'completed' && <form onSubmit={(e) => { e.preventDefault(); const draft = testDrafts[step._id]; updateStep.mutate({ planId: row._id, stepId: step._id, data: { test: { testedAt: draft.testedAt, result: draft.result, note: draft.note || '', visibleToStudent: !!draft.visibleToStudent } } }) }} className="mt-3 grid gap-2 sm:grid-cols-2"><label>تاريخ اختبار خارج المنصة<input required type="date" value={testDrafts[step._id]?.testedAt || ''} onChange={(e) => setTestDrafts({ ...testDrafts, [step._id]: { ...testDrafts[step._id], testedAt: e.target.value } })} className={input} /></label><label>النتيجة كما وردت<input required maxLength={500} value={testDrafts[step._id]?.result || ''} onChange={(e) => setTestDrafts({ ...testDrafts, [step._id]: { ...testDrafts[step._id], result: e.target.value } })} className={input} /></label><label className="sm:col-span-2">ملاحظة<input maxLength={1000} value={testDrafts[step._id]?.note || ''} onChange={(e) => setTestDrafts({ ...testDrafts, [step._id]: { ...testDrafts[step._id], note: e.target.value } })} className={input} /></label><label className="flex items-center gap-2"><input type="checkbox" checked={!!testDrafts[step._id]?.visibleToStudent} onChange={(e) => setTestDrafts({ ...testDrafts, [step._id]: { ...testDrafts[step._id], visibleToStudent: e.target.checked } })} />إظهار النتيجة للطالب</label><button disabled={updateStep.isPending} className="min-h-11 rounded-lg bg-violet-700 px-3 font-bold text-white">تسجيل النتيجة</button></form>}
          </div>)}</div>
        </article>)}
        <form onSubmit={(e) => { e.preventDefault(); save.mutate() }} className="rounded-xl border border-violet-100 bg-violet-50/40 p-4"><h3 className="font-bold">{(plans.data?.data || []).some((row) => row.subjectKey === form.subjectKey) ? 'تعديل خطة المنهج' : 'خطة جديدة'}</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm">المجال<select required value={form.subjectKey} onChange={(e) => setForm({ ...initial, studentId, subjectKey: e.target.value })} className={input}><option value="">اختر المجال</option>{(subjects.data?.data || []).map((subject) => <option key={subject.key} value={subject.key}>{subject.nameAr}</option>)}</select></label><label className="text-sm">المقرر المرتبط<select value={form.courseId} onChange={(e) => setForm({ ...form, courseId: e.target.value })} className={input}><option value="">خطة فردية</option>{(courses.data || []).map((course) => <option key={course._id} value={course._id}>{course.nameAr}</option>)}</select></label><label className="text-sm">مستوى الطالب<input required maxLength={200} value={form.level} onChange={(e) => setForm({ ...form, level: e.target.value })} className={input} /></label><label className="text-sm">الهدف<input required maxLength={1000} value={form.goal} onChange={(e) => setForm({ ...form, goal: e.target.value })} className={input} /></label><label className="text-sm">الخطوة القادمة<input maxLength={1000} value={form.nextStep} onChange={(e) => setForm({ ...form, nextStep: e.target.value })} className={input} /></label><label className="text-sm">احتياج فردي داخلي<input maxLength={1000} value={form.individualNeeds} onChange={(e) => setForm({ ...form, individualNeeds: e.target.value })} className={input} /></label></div>
          <div className="mt-4"><p className="text-sm font-bold">مراحل المنهج</p><div className="mt-2 flex gap-2"><input value={milestoneTitle} onChange={(e) => setMilestoneTitle(e.target.value)} maxLength={200} className={input} placeholder="اسم المرحلة" /><button type="button" onClick={() => { if (milestoneTitle.trim()) { setForm({ ...form, milestones: [...form.milestones, { title: milestoneTitle.trim() }] }); setMilestoneTitle('') } }} className="min-h-11 rounded-lg border px-4">إضافة</button></div><div className="mt-2 flex flex-wrap gap-2">{form.milestones.map((step, index) => <span key={step._id || index} className="rounded-lg bg-white px-3 py-2 text-xs">{step.title}</span>)}</div></div>
          <div className="mt-4"><p className="text-sm font-bold">مواد مساعدة</p><div className="mt-2 grid gap-2 md:grid-cols-[minmax(100px,1fr)_minmax(180px,2fr)_160px_auto]"><input value={material.title} onChange={(e) => setMaterial({ ...material, title: e.target.value })} className={input} placeholder="اسم المادة" /><input type="url" value={material.url} onChange={(e) => setMaterial({ ...material, url: e.target.value })} className={input} placeholder="رابط HTTPS" /><select aria-label="من يرى المادة" value={material.visibility} onChange={(e) => setMaterial({ ...material, visibility: e.target.value })} className={input}><option value="teacher_only">للمعلم فقط</option><option value="shared">للمعلم والطالب</option></select><button type="button" onClick={() => { if (material.title.trim() && material.url.startsWith('https://')) { setForm({ ...form, materialLinks: [...form.materialLinks, material] }); setMaterial({ title: '', url: '', visibility: 'teacher_only' }) } }} className="min-h-11 rounded-lg border px-3">إضافة</button></div><div className="mt-2 flex flex-wrap gap-2">{form.materialLinks.map((link, index) => <button key={`${link.url}-${index}`} type="button" onClick={() => setForm({ ...form, materialLinks: form.materialLinks.filter((_, i) => i !== index) })} className="rounded-lg bg-white px-3 py-2 text-xs" title="إزالة الرابط">{link.title} ×</button>)}</div></div>
          <button disabled={save.isPending || !form.subjectKey} className="mt-4 min-h-11 rounded-xl bg-violet-700 px-5 font-bold text-white disabled:opacity-50">{save.isPending ? 'جارٍ الحفظ...' : 'حفظ الخطة'}</button><p className="mt-2 text-xs text-gray-500">ينشر المدير الخطة بعد مراجعتها. الاختبار يُجرى خارج المنصة وتُسجل نتيجته هنا يدويًا.</p>
        </form>
        {overview.isError && <p role="alert" className="text-sm text-red-700">تعذر تحميل الإنجازات</p>}
        {overview.data && <div className="grid gap-3 sm:grid-cols-3">{[['آخر الحفظ', overview.data.memorized], ['آخر المراجعة', overview.data.revised], ['تقييمات الطالب', overview.data.evaluations]].map(([title, rows]) => <div key={title} className="rounded-xl border border-gray-100 p-4"><h3 className="font-bold">{title}</h3><p className="mt-1 text-xs text-gray-500">آخر {rows.length} سجلات من المصدر الأصلي</p><div className="mt-3 space-y-2">{rows.map((item) => <p key={item._id} className="rounded-lg bg-gray-50 p-2 text-xs">{item.surahNumber ? `سورة ${item.surahNumber} · ${item.fromAyah}–${item.toAyah}` : `${item.type} · ${item.score}/10`} · {format(item.recordedAt || item.createdAt)}</p>)}</div></div>)}</div>}
        {overview.data?.observations?.length > 0 && <div className="rounded-xl border border-gray-100 p-4"><h3 className="font-bold">ملاحظات المشرف الأكاديمي على الطالب</h3><div className="mt-3 space-y-2">{overview.data.observations.map((row) => <p key={row._id} className="rounded-lg bg-gray-50 p-3 text-sm"><strong>{format(row.scheduledAt)}</strong> · المستوى: {row.studentLevel || '—'} {row.observations && `· ${row.observations}`}</p>)}</div></div>}
      </div>}
    </section>
    <section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">متابعة المعلمين</h2><p className="mt-1 text-sm text-gray-500">التقييم يأتي من تقارير متابعة الحصص الفعلية، دون نقاط ترتيب إضافية.</p><div className="mt-3 grid gap-3 sm:grid-cols-2">{leader && <input value={teacherSearch} onChange={(e) => { setTeacherSearch(e.target.value); setTeacherId('') }} className={input} placeholder="ابحث عن معلم" />}<select value={teacherId} onChange={(e) => setTeacherId(e.target.value)} className={input}><option value="">اختر المعلم</option>{(leader ? (teachers.data || []).filter((row) => row.role === 'teacher') : (assignments.data?.data || []).map((row) => row.teacherId).filter(Boolean)).map((row) => <option key={row._id} value={row._id}>{name(row)}</option>)}</select></div>{teacher.isError && <p role="alert" className="mt-3 text-sm text-red-700">تعذر تحميل ملف المعلم</p>}{teacher.data && <div className="mt-4"><h3 className="font-bold">{name(teacher.data.teacher)} · {teacher.data.studentCount} طالب في الجداول · {teacher.data.total} تقرير متابعة</h3><p className="mt-1 text-xs text-gray-500">التخصصات: {teacher.data.teacher.specializations?.join('، ') || '—'}</p><div className="mt-3 space-y-2">{teacher.data.reports.map((row) => <div key={row._id} className="rounded-xl bg-gray-50 p-3 text-sm"><strong>{format(row.scheduledAt)} · {rating[row.rating] || 'بلا تقييم'}</strong><p className="mt-1">نقاط القوة: {row.strengths || '—'}</p><p>التطوير: {row.improvements || '—'}</p>{row.followUpNeeded && <p>المتابعة: {row.nextFollowUpPoint || 'مطلوبة'}</p>}<p className="text-xs text-gray-500">رد المعلم: {row.teacherReplyStatus || 'لم يرد بعد'} {row.teacherReply || ''}</p></div>)}</div></div>}</section>
    {leader && <section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">متابعة المشرفين الأكاديميين</h2><p className="mt-1 text-sm text-gray-500">تقارير المتابعة والتكليفات والتوجيهات السابقة لكل مشرف.</p><select aria-label="اختر المشرف الأكاديمي" value={supervisorId} onChange={(e) => setSupervisorId(e.target.value)} className={`mt-3 max-w-md ${input}`}><option value="">اختر مشرفًا</option>{(supervisors.data?.data || []).filter((row) => row.supervisionPosition === 'supervisor').map((row) => <option key={row._id} value={row._id}>{name(row)}</option>)}</select>{supervisorProfile.isError && <p role="alert" className="mt-3 text-sm text-red-700">تعذر تحميل ملف المشرف</p>}{supervisorProfile.data && <div className="mt-4 space-y-3 text-sm"><h3 className="font-bold">{name(supervisorProfile.data.staff)} · {supervisorProfile.data.assignmentCount} تكليف جارٍ · {supervisorProfile.data.reportCount} تقرير متابعة</h3><p className="text-xs text-gray-500">الفئات: {supervisorProfile.data.staff.supervisionCategories?.join('، ') || '—'}</p><div className="grid gap-3 md:grid-cols-2"><div><h4 className="font-semibold">آخر التقارير</h4>{supervisorProfile.data.reports.map((row) => <p key={row._id} className="mt-2 rounded-lg bg-gray-50 p-2">{format(row.scheduledAt)} · {rating[row.rating] || 'بدون تقييم'} {row.followUpNeeded ? '· متابعة مطلوبة' : ''}</p>)}</div><div><h4 className="font-semibold">التوجيهات السابقة</h4>{supervisorProfile.data.directives.map((row) => <p key={row._id} className="mt-2 rounded-lg bg-gray-50 p-2">{row.directiveId?.title} · {row.status} {row.reply && `· ${row.reply}`}</p>)}</div></div></div>}</section>}
    {teacher.data?.directives?.length > 0 && <section className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm"><h2 className="font-bold">سجل توجيهات المعلم</h2><div className="mt-3 space-y-2">{teacher.data.directives.map((row) => <p key={row._id} className="rounded-xl bg-gray-50 p-3 text-sm"><strong>{row.directiveId?.title}</strong> · {row.status} {row.reply && `· ${row.reply}`} {row.verifiedAt && '· اعتمد المدير التنفيذ'}</p>)}</div></section>}
    {leader && teacherId && teacher.data && <AcademicDevelopmentPanel key={`teacher-${teacherId}`} personId={teacherId} cases={teacher.data.development} onSaved={() => teacher.refetch()} />}
    {leader && supervisorId && supervisorProfile.data && <AcademicDevelopmentPanel key={`supervisor-${supervisorId}`} personId={supervisorId} cases={supervisorProfile.data.development} onSaved={() => supervisorProfile.refetch()} />}
  </div>
}
