export const QK = {
  ME: ['auth', 'me'],
  STUDENTS: (params) => ['students', params],
  STUDENT: (id) => ['students', id],
  STUDENT_PROGRESS: (id) => ['students', id, 'progress'],
  STUDENT_STATS: (id) => ['students', id, 'stats'],
  TEACHERS: (params) => ['teachers', params],
  TEACHER: (id) => ['teachers', id],
  COURSES: (params) => ['courses', params],
  COURSE: (id) => ['courses', id],
  LEVELS: (params) => ['levels', params],
  SESSIONS: (params) => ['sessions', params],
  SESSION: (id) => ['sessions', id],
  UPCOMING_SESSIONS: ['sessions', 'upcoming'],
  ATTENDANCE: (params) => ['attendance', params],
  HOMEWORK: (params) => ['homework', params],
  HOMEWORK_SUBMISSIONS: (id) => ['homework', id, 'submissions'],
  EVALUATIONS: (params) => ['evaluations', params],
  MEMORIZATION: (studentId) => ['memorization', studentId],
  REVISION: (studentId) => ['revision', studentId],
  PACKAGES: ['packages'],
  SUCCESS_STORIES: ['success-stories'],
  PACKAGE: (id) => ['packages', id],
  SUBSCRIPTIONS: (params) => ['subscriptions', params],
  MY_SUBSCRIPTION: ['subscriptions', 'me'],
  NOTIFICATIONS: ['notifications', 'me'],
  NOTIFICATION_COUNT: ['notifications', 'count'],
  AI_CONVERSATIONS: ['ai', 'conversations'],
  AI_CONVERSATION: (id) => ['ai', 'conversations', id],
  WEBSITE: (section) => ['website', section],
  REPORTS: (type) => ['reports', type],
}
