import api from '../utils/api.js'

export const supervisionService = {
  periodicMetrics: (params) => api.get('/supervision/periodic-metrics', { params }).then((r) => r.data.data),
  periodicReports: (params) => api.get('/supervision/periodic-reports', { params }).then((r) => r.data),
  periodicReport: (id) => api.get(`/supervision/periodic-reports/${id}`).then((r) => r.data.data),
  savePeriodicReport: (data) => api.post('/supervision/periodic-reports', data),
  submitPeriodicReport: (id) => api.post(`/supervision/periodic-reports/${id}/submit`),
  reviewPeriodicReport: (id, data) => api.post(`/supervision/periodic-reports/${id}/review`, data),
  correctPeriodicReport: (id, data) => api.post(`/supervision/periodic-reports/${id}/correct`, data),
  academicSearch: (q) => api.get('/supervision/academic-search', { params: { q } }).then((r) => r.data.data),
  academicRecognition: (start) => api.get('/supervision/academic-recognition', { params: { start } }).then((r) => r.data.data),
  saveAcademicRecognition: (data) => api.put('/supervision/academic-recognition', data),
  academicStudents: (search) => api.get('/supervision/academic-students/search', { params: { search } }).then((r) => r.data.data),
  studentAcademicOverview: (studentId) => api.get(`/supervision/academic-students/${studentId}/overview`).then((r) => r.data.data),
  teacherAcademicOverview: (teacherId) => api.get(`/supervision/academic-teachers/${teacherId}/overview`).then((r) => r.data.data),
  supervisorAcademicOverview: (supervisorId) => api.get(`/supervision/academic-supervisors/${supervisorId}/overview`).then((r) => r.data.data),
  createAcademicDevelopment: (data) => api.post('/supervision/academic-development', data),
  updateAcademicDevelopment: (id, data) => api.patch(`/supervision/academic-development/${id}`, data),
  academicPlans: (params) => api.get('/supervision/academic-plans', { params }).then((r) => r.data),
  saveAcademicPlan: (data) => api.post('/supervision/academic-plans', data),
  publishAcademicPlan: (id, status) => api.patch(`/supervision/academic-plans/${id}/status`, { status }),
  updateAcademicMilestone: (planId, milestoneId, data) => api.patch(`/supervision/academic-plans/${planId}/milestones/${milestoneId}`, data),
  academicDirectives: (params) => api.get('/supervision/academic-directives', { params }).then((r) => r.data),
  academicDirectiveRecipientsSearch: (search) => api.get('/supervision/academic-directive-recipients/search', { params: { search } }).then((r) => r.data.data),
  academicDirectiveReceipts: (id, params) => api.get(`/supervision/academic-directives/${id}/receipts`, { params }).then((r) => r.data),
  createAcademicDirective: (data) => api.post('/supervision/academic-directives', data),
  replyAcademicDirective: (id, data) => api.post(`/supervision/academic-directives/${id}/reply`, data),
  verifyAcademicDirective: (id) => api.post(`/supervision/academic-directives/${id}/verify`),
  academicReports: (params) => api.get('/supervision/academic-reports', { params }).then((r) => r.data),
  academicReport: (id) => api.get(`/supervision/academic-reports/${id}`).then((r) => r.data.data),
  saveAcademicReport: (sessionId, data) => api.put(`/supervision/academic-reports/session/${sessionId}`, data),
  submitAcademicReport: (id) => api.post(`/supervision/academic-reports/${id}/submit`),
  reviewAcademicReport: (id, data) => api.post(`/supervision/academic-reports/${id}/review`, data),
  correctAcademicReport: (id, data) => api.patch(`/supervision/academic-reports/${id}/correct`, data),
  teacherGuidance: (params) => api.get('/supervision/teacher-guidance', { params }).then((r) => r.data),
  replyGuidance: (id, data) => api.post(`/supervision/teacher-guidance/${id}/reply`, data),
  shiftRecords: (params) => api.get('/supervision/shift-records', { params }).then((r) => r.data),
  shiftRecord: (shiftId, memberId) => api.get(`/supervision/shift-records/${shiftId}`, { params: memberId ? { memberId } : {} }).then((r) => r.data.data),
  shiftHandoffs: (team) => api.get('/supervision/shift-handoffs', { params: { team } }).then((r) => r.data.data),
  checkInShift: (shiftId) => api.post(`/supervision/shift-records/${shiftId}/check-in`),
  checkOutShift: (shiftId) => api.post(`/supervision/shift-records/${shiftId}/check-out`),
  handoffShift: (shiftId, note) => api.post(`/supervision/shift-records/${shiftId}/handoff`, { note }),
  saveShiftReportDraft: (shiftId, analysis) => api.patch(`/supervision/shift-records/${shiftId}/report-draft`, { analysis }),
  submitShiftReport: (shiftId, analysis) => api.post(`/supervision/shift-records/${shiftId}/report`, { analysis }),
  newStudents: (params) => api.get('/supervision/new-students', { params }).then((r) => r.data),
  stabilizeStudent: (studentId, note) => api.post(`/supervision/new-students/${studentId}/stabilize`, { note }),
  dailySessions: (params) => api.get('/supervision/daily-sessions', { params }).then((r) => r.data),
  exceptions: (params) => api.get('/supervision/exceptions', { params }).then((r) => r.data),
  createException: (data) => api.post('/supervision/exceptions', data),
  applyException: (id, data) => api.post(`/supervision/exceptions/${id}/apply`, data),
  retryException: (id) => api.post(`/supervision/exceptions/${id}/retry`),
  resolveException: (id, resolution) => api.post(`/supervision/exceptions/${id}/resolve`, { resolution }),
  reassignException: (id, data) => api.patch(`/supervision/exceptions/${id}/owner`, data),
  adjustmentRequests: (params) => api.get('/supervision/adjustment-requests', { params }).then((r) => r.data),
  requestAdjustment: (data) => api.post('/supervision/adjustment-requests', data),
  decideAdjustment: (id, data) => api.post(`/supervision/adjustment-requests/${id}/decision`, data),
  retryAdjustment: (id) => api.post(`/supervision/adjustment-requests/${id}/retry`),
  dispatchDay: (data) => api.post('/supervision/daily-dispatch', data),
  createDailyAction: (data) => api.post('/supervision/daily-actions', data),
  resolveDailyAction: (id, resolution) => api.post(`/supervision/daily-actions/${id}/resolve`, { resolution }),
  remindTeacherReport: (sessionId, team) => api.post(`/supervision/sessions/${sessionId}/remind-report`, { team }),
  updateReadiness: (sessionId, aspect, state) => api.patch(`/supervision/sessions/${sessionId}/readiness`, { aspect, state }),
  coverage: (params) => api.get('/supervision/coverage', { params }).then((r) => r.data),
  activity: (params) => api.get('/supervision/activity', { params }).then((r) => r.data),
  settings: (params) => api.get('/supervision/settings', { params }).then((r) => r.data),
  saveSettings: (data) => api.put('/supervision/settings', data),
  updatePerson: (id, data) => api.patch(`/supervision/people/${id}`, data),
  subjects: () => api.get('/teaching-subjects').then((r) => r.data),
  people: (params) => api.get('/supervision/people', { params }).then((r) => r.data),
  teachers: (params) => api.get('/supervision/teachers', { params }).then((r) => r.data),
  shifts: (params) => api.get('/supervision/shifts', { params }).then((r) => r.data),
  createShift: (data) => api.post('/supervision/shifts', data),
  updateShift: (id, data) => api.patch(`/supervision/shifts/${id}`, data),
  cancelShift: (id) => api.post(`/supervision/shifts/${id}/cancel`),
  assignments: (params) => api.get('/supervision/assignments', { params }).then((r) => r.data),
  createAssignment: (data) => api.post('/supervision/assignments', data),
  replaceAssignment: (id, data) => api.post(`/supervision/assignments/${id}/replace`, data),
  assignmentStudents: (id, params) => api.get(`/supervision/assignments/${id}/students`, { params }).then((r) => r.data),
}
